### ISSUE TITLE
Unit issue in "2010 TOYOTA YARIS (CCSA V2j)"

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1034]
**Describe the bug**
The GAS CHARACTERISTICS of "2010 TOYOTA YARIS (CCSA V2j)" are a factor 1000 to small.

**To Reproduce**
Run the starter with the "2010 TOYOTA YARIS (CCSA V2j)" demo model and look into the output file.

**Expected behavior**
```
MOLECULAR WEIGHT  . . . . . . . . . . .=  0.2897E-04
UNIVERSAL GAS CONSTANT. . . . . . . . .=  0.8314E+04
```

**Output**
In "YarisOpenRadioss.key" is the unit definition:
```
 10 *CONTROL_UNITS
 11 $LENGTH   TIME      MASS      TEMP
 12 $#  length      time      mass      temp
 13 mm        sec       mtrc_ton  k
```

In "YarisOpenRadioss_0000.out" is the units system:
```
   57457     WORK UNIT SYSTEM . . . . . . ( N.A, N.A, N.A ) 1.0000000000000E+00 1.0000000000000E+00 1.0000000000000E+00
   57458     INPUT UNIT SYSTEM  . . . . . ( N.A, N.A, N.A ) 1.0000000000000E+00 1.0000000000000E+00 1.0000000000000E+00
   57459     UNIT SYSTEM, ID = 1000000001 ( N.A, N.A, N.A ) 1.0000000000000E+00 1.0000000000000E+00 1.0000000000000E+00
```
and then:
```
   97907        GAS CHARACTERISTICS
   97908        -------------------
   97909
   97910
   97911      GAS TYPE. . . . . . . . . . . . . . . .=  User
   97912      SPECIFIC HEAT AT CONSTANT PRESSURE CP .=  0.1004E+10
   97913      SPECIFIC HEAT AT CONSTANT VOLUME CV. . =  0.7170E+09
   97914      MOLECULAR WEIGHT  . . . . . . . . . . .=  0.2897E-07
   97915      UNIVERSAL GAS CONSTANT. . . . . . . . .=  0.8314E+01
```
**Desktop (please complete the following information):**
 - Version [42e2b4c697417d781a607ef2481efbfadfd697c0]
- Hardware [which CPU]
Linux:Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3498 MHz,  64217 MB RAM,      0 MB swap
STARTER RUNNING ON    1 THREAD

**Additional context**
This seems to be a consequence error of /UNITS in connection with *INCLUDE.

**Comment by sebastienVilleneuve** [comment]
I let you restest with cb8cf091b51f6b7395d0d8431ea7c718036665c9

Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
We have now :
![image](https://user-images.githubusercontent.com/100404030/222350911-cede4f3e-2ded-42dd-8144-8d09adc52445.png)

I think we can consider this issue as solved, I let you confirm.

Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
Moving *CONTROL_UNIT in the main model , is giving expected results :

![image](https://user-images.githubusercontent.com/100404030/222354241-8f89c6db-9b94-4c12-966d-c982fdeec49e.png)

I think we can solve the issue

Thanks,
Sébastien
