### ISSUE TITLE
radioss cannot recognize lsdyna option *CONSTRAINED_NODE_SET_ID

### ISSUE THREAD

**Issue by zhukai242** [OpenRadioss/OpenRadioss#1075]
**Describe the bug**
when i apply a lsdyna model contains *CONSTRAINED_NODE_SET_ID , radioss error happened

**Output**
ERROR ID : 100210
** ERROR IN INPUT OPTIONS
DESCRIPTION :
-- BLOCK: *CONSTRAINED_NODE_SET_ID
-- LINE: *CONSTRAINED_NODE_SET_ID
Unrecognized option: *CONSTRAINED_NODE_SET_ID

**Comment by sebastienVilleneuve** [comment]
Hi @zhukai242 

I confirm this is not supported yet , but work is ongoing .

Thanks,
Sébastien

**Comment by zhukai242** [comment]
thanks @sebastienVilleneuve 
i have another question 
AIRBAG_HYBRID_ID. also not support，
how to do in .key file  
that i can run in radioss

**Comment by sebastienVilleneuve** [comment]
Hi @zhukai242 

Implemented with 
31d7d172b28f34e0377ea6a175a99743f950ebe9

Sébastien
