### ISSUE TITLE
Syntax for /INCLUDE_DYNA

### ISSUE THREAD

**Issue by DavidR-Vortex** [OpenRadioss/OpenRadioss#1090]
Hi,

I'm having an issue getting /INCLUDE_DYNA to process in starter. I'm using the most recent starter engine binary at the time of writing. Is there any syntax that I am missing/using incorrectly?

![image](https://user-images.githubusercontent.com/114189884/217055738-9a63cc78-8997-4b12-9aed-1acbb96b208a.png)

**Comment by OpenDevAccount** [comment]
Hi,

Input version of your main deck is 2017, but the keyword was added from input 2022.
So , replacing 2017 by 2022 should solve the issue.

Note that this dev is still in développement  phase .

Sebastien

**Comment by DavidR-Vortex** [comment]
Thanks Sebastien,

I had already tried changing it to 2022 but no luck:

![image](https://user-images.githubusercontent.com/114189884/217075988-aeafbaae-49df-4ab8-a2c7-4cb350515c4d.png)

**Comment by DavidR-Vortex** [comment]
Ah that was it thank you. I had updated them yesterday but not today.

Starter ran as before, but I'm not getting a 0001.rad file like I was before. I'm getting a DYNA_INCLUDE_0001.rad which is blank and causes engine to fail. If I manually create the 0001.rad from the equivalent Dyna only run I had previously engine runs normally.

![image](https://user-images.githubusercontent.com/114189884/217093363-6a85df0e-039b-4c34-afd9-914ffc5e7b83.png)

**Comment by DavidR-Vortex** [comment]
So with the workaround I'm current running the Camry example with AMS active which is really cool!

**Comment by sebastienVilleneuve** [comment]
Hi @DavidR-Vortex 

For information, this DYNA_INCLUDE_0001.rad is just here to help user to generate your 'main' 1.rad file.
Thanks again for the interest to this new option.

Can I close this issue now ?

Regards,
Sébastien

**Comment by DavidR-Vortex** [comment]
Hi @sebastienVilleneuve 

Yes thank-you, it can be closed. There is an issue with rigid wall definitions but I'll create a new bug report for that,

Kind regards,
David
