### ISSUE TITLE
/INCLUDE_DYNA *RIGIDWALL Unit Issue

### ISSUE THREAD

**Issue by DavidR-Vortex** [OpenRadioss/OpenRadioss#1093]
**Describe the bug**
Running the Toyota Camry model using /INCLUDE_DYNA

![image](https://user-images.githubusercontent.com/114189884/217367460-cb1a6979-b065-46db-b27b-ba832ec3aab6.png)

CamryOpenRadioss.key contains:

![image](https://user-images.githubusercontent.com/114189884/217367378-140f71c8-6313-48f8-964c-9dab54a5e15d.png)

Model runs, however rigid wall definitions are not mapped correctly.

![image](https://user-images.githubusercontent.com/114189884/217367653-00617b2d-022e-41b0-a3c0-7195fc02b6be.png)

![image](https://user-images.githubusercontent.com/114189884/217367751-1a6863e0-1c49-41c6-8eee-51bc706e0adf.png)

Vehicle is correct size

**Comment by sebastienVilleneuve** [comment]
Hi @DavidR-Vortex 

Thanks so much for your interest , I will take care of this.

Have a good day.
Sébastien

**Comment by DavidR-Vortex** [comment]
Thanks Sébastien,

In general what is the best way to follow an issue's progress once it has been raised (I'm new to Github),

Many thanks,
David

**Comment by sebastienVilleneuve** [comment]
Hi,

When the pb will be solved ,This issue will be closed with reference to the commit that is correcting the issue.

Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
Hi,

I let you retest with cb8cf091b51f6b7395d0d8431ea7c718036665c9

Thanks,
Sébastien

**Comment by DavidR-Vortex** [comment]
Hi Sébastien, I've downloaded the latest release and updated the Win64 DLL from cb8cf09 but still having the same issue. I've uploaded my input files, (with the absence of the Camry model due to it's size, it is however unmodified from the example kindly provided by you guys) to assist.
[input_files.zip](https://github.com/OpenRadioss/OpenRadioss/files/10817420/input_files.zip)

Many thanks,
David
