### ISSUE TITLE
Serious Issue: The Starter crashed with segfault in a 2D model with /INTER/TYPE11

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1126]
**Describe the bug**
The Starter crashed with segfault.

**To Reproduce**
Run the starter with the "lee_0000.rad" out of the attached archive 
[issue.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/10741780/issue.tar.gz)

**Expected behavior**
Should not crash.

**Output**
'''
 +=============================================================+
 |     ABNORMAL END                                            |
 |          Segmentation Violation                             |
 |     TRACE BACK :                                            |
 +=============================================================+
   INTERFACES
 +=============================================================+

ERROR ID :    760
** ERROR TRAPPED

 RADIOSS STOP DUE TO INPUT ERROR
###########
With dbg the following information is given:

 .. INTERFACE BUFFER INITIALIZATION                                                      

Program received signal SIGSEGV, Segmentation fault.
inint0 (x=..., irect=..., nseg=..., nod2seg=..., nsv=..., msr=..., iloc=..., nmn=3, nsn=3, nrt=2) at /opt2/OpenRadioss/starter/source/interfaces/interf1/inint0.F:80
80                     IF(NOD2SEG(L)/=0) II=II+1
'''
**Desktop (please complete the following information):**
- Version [2a35aba0b9867442f0e71d526715e43df6257eb6]
- Hardware [which CPU]
Linux: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3498 MHz,  64217 MB RAM,      0 MB swap
STARTER RUNNING ON    1 THREAD

**Additional context**
None.

**Comment by laurent-altr** [comment]
Hello @SonSiont , 

I am not sure that interface TYPE11 is relevant in a 2D model, maybe @PaulAltair or @MarianBulla can confirm.
Anyway, the segmentation violation has to be fixed. 

Thank you

**Comment by sebastienVilleneuve** [comment]
Hi @laurent-altr 

you'r right :
https://2022.help.altair.com/2022.1/hwsolvers/rad/topics/solvers/rad/2d_3d_analysis_options_starter_r.htm

![image](https://user-images.githubusercontent.com/100404030/219303649-1fac66a1-f9e0-4d92-8db6-274f3a8ec0e1.png)

**Comment by MarianBulla** [comment]
Hello @SonSiont, 
do you really want to perforn a 2D (axisymetric) analysis or do you just want to use "sipmle" plates and checking the edge-to-edge contact ?

Thanks and best regards,
Marian

**Comment by SonSiont** [comment]
Hi Marian,

it was my fault. With INTER3 it works.
After fix the MAT and the units I got a result.
Questionable is the output of the pressure - should I calculate this myself from the stress tensor?
Also I was looking for the burning fraction as in Mat 5&51 - is it possible to output something?
Thanks

**Comment by MarianBulla** [comment]
Hi @SonSiont, 
depends on you postprocessor, computing the pressure is usually embedded.
If you want to do it by yourself (e.g. creating a scripting or anything else) works, too.
You just need the trace divided by 3 (maybe changing the sign, but this is a question of flavor).
From animation files, you can try to request /ANIM/ELEM/P

For the burning fraction in MAT5&MAT51, I'm not sure. Did you double check it in the manual ?
Thanks and best regards,
Marian

**Comment by MarianBulla** [comment]
Hi @SonSiont,
would:  **/ANIM/BRICK/BFRAC** for the burning fraction visualization work for you ?
Thanks and best regards,
Marian

**Comment by sebastienVilleneuve** [comment]
for information; I 've added a new error message when using 2D analysis + not supported interface 
e4e174cc10154650b453bb4a6419c34f72f992b2

Sébastien
