### ISSUE TITLE
Node contact forces are all written as "0" into all anim files

### ISSUE THREAD

**Issue by BastiLoe** [OpenRadioss/OpenRadioss#1180]
**Describe the bug**
Node contact forces are all written as "0" into al anim files

**To Reproduce**
1. Run a OpenRadioss-Job with output to animation-files
2. Post-process nodal contact forces - they are "0" for all nodes in all animation files

**Expected behavior**
Should write the correct nodal contact forces to animation files

**Comment by MarianBulla** [comment]
Hello,
thank you for using OpenRadioss.
Can you provide me some details about your issue, please ?
Usually it is not a problem to get the contact forces in the animations files by addind this request within the engine file.
Thanks and best regards,
Marian

**Comment by BastiLoe** [comment]
It's not a problem at all - from my understanding they don't even need a special request. And the are in all animation files .... Unfortunately they are zero for all nodes in all animation files .....

**Comment by MarianBulla** [comment]
Please have a look, what I'm obtaining (see attached screenshot).
Hope it helps you ?
![image](https://user-images.githubusercontent.com/105412502/222721937-67b34aa1-6e9a-4a34-a2d7-b57d36764ef3.png)

**Comment by BastiLoe** [comment]
I can confirm it is working with Commit-ID e10539f from March 3th, 2023. My work was based on Commit-ID 82c9be5 from Sept. 29,2022 which has this issue.

**Comment by MarianBulla** [comment]
Great ! 
I'm happy, that it is finaly working on your side. 
Thank you very much for your positive feedback.
Thanks and best regards,
Marian
