### ISSUE TITLE
th_to_csv_win64 does not convert properly

### ISSUE THREAD

**Issue by danielperezrapela** [OpenRadioss/OpenRadioss#1213]
**Bug description**
I am running a very simple bouncing ball simulation using LS-Dyna inputs. The simulation seems to run correctly. I can convert the ANIMs to VTK and the ball moves as expected. However, when I convert the th file to csv, it is clear that the conversion is wrong. As you can see in the attached file, all outputs seem to be wrong. This is most clear in the "time" output that shows "0" in multiple lines. Can anybody give me some idea of why this may be happening? 

**To Reproduce**
You can reproduce this just by running the attached file ("Bouncing_Radioss.key") in SMP single precision and applying the th_to_csv_win64 to the T01 output.

**Expected behavior**
The output signals show be coherent with what is happening in the simulation. The time vector should be ordered and show all the output times.

**Desktop (please complete the following information):**
- Version [commit id]: 892a60a5fa9cf1c13b43afb6ff10414de23f01f2
- Hardware [which CPU]: Intel(R)_Core(TM)_i7-3612QM_CPU_@_2.10GHz
- Configuration [number of OpenMP threads, and MPI tasks]: SMP single precission 1 thread

[Bouncing_ball.zip](https://github.com/OpenRadioss/OpenRadioss/files/10951230/Bouncing_ball.zip)

**Comment by sebastienVilleneuve** [comment]
Hi @danielperezrapela 

After investigation, issue is not in converter itself , but more in the starter.
Removing *DATABASE_ABSTAT card in main.k , the csv looks good

![image](https://user-images.githubusercontent.com/100404030/224655226-1ac16e6b-1e2c-4d38-9134-645cea39d099.png)

![image](https://user-images.githubusercontent.com/100404030/224654779-0620102a-668f-43fd-88fe-7c74db046dcb.png)

I will work to correct this issue .

Thanks a lot for your interest and your feedback 
Sébastien

**Comment by sebastienVilleneuve** [comment]
solved with 5917de629e12833165edcb8cf0072a0c7fdf73f2
