### ISSUE TITLE
The window platform gdb cannot be debugged

### ISSUE THREAD

**Issue by lzh-maker** [OpenRadioss/OpenRadioss#1232]
Hello everyone：
I have successfully compiled the starter and engine executables under the Windows platform, added the -debug=1 flag when compiling, and the compiled executable file name suffix contains "_db", but when I tried to debug it with gdb, I found that there was no debug flag and could not set breakpoints, as shown below. Why is that? Isn't the compiled debug version?
![0E19A10B-650B-4429-8C81-82BF05C1BD11](https://user-images.githubusercontent.com/76392842/225322705-da16f404-745f-4f11-93f6-9ba73badc344.jpeg)

**Comment by lzh-maker** [comment]
Can you elaborate on how to use Visual Studio debugging, I used to use Visual Studio debugging based on .sln projects, but now only makefiles and executables, how to use Visual Studio debugging. Is it debugging with vscode+msvc?

**Comment by OlivierWienholtz** [comment]
As we have Linux/Windows Project, we choose Cmake for build to have unique method between Linux & Windows...
And yes... We come from the Linux World :)

CMake can be read by Visual Studio if you have installed the CMake package for Windows. 
We are finalizing configuration files for VS (Json format) which will be read & configurations will be set.
From there you can generate Debug versions, .pdb files will also be generated.

**Comment by OlivierWienholtz** [comment]
Hello,

Id did some adjustments on the Windows builds with commit ID 8843bbb35cf7b0fbe9e8af5c7197f2acb7db7ba7
PDB files are now created.

you will find the .pdb files in : 

When building in Visual Studio : 

[OpenRadiossRoot]\vs_build_win64\Starter_x64-Debug\starter
[OpenRadiossRoot]\vs_build_win64\Engine_x64-Debug\engine

When building using build_windows.bat : 
 [OpenRadiossRoot]\starter\cbuild_win64_db_ninja
 [OpenRadiossRoot]\engine\cbuild_win64_db_ninja


In the Entire Visual Studio Workflow : when building in Visual Studio:

* Use the Debug configurations to build 
* Set in the Tools Menu: 
  [Tools] [Options] 
      Debugging
      Symbols

       Those 2 directories & select them.

* After Selecting in the Startup Item  : 
    starter_win64_db or engine_win64_db 
  You can add in [Debug]\[Debug and Launch Settings] your settings to launch the Debug sections.

**Comment by OlivierWienholtz** [comment]
Some new comments : 
The Workflow how to build OpenRadioss is explained here:
https://github.com/OpenRadioss/OpenRadioss/blob/main/HOWTO.md#build-openradioss-with-visual-studio

The Workflow how to use the Debugger is maintained here
https://github.com/OpenRadioss/OpenRadioss/blob/main/doc/Visual_Studio_Debugger.md

**Comment by lzh-maker** [comment]
Thank you very much，I have debugged the project successfully！
