### ISSUE TITLE
*DATABASE_BINARY_D3DRLF 

### ISSUE THREAD

**Issue by DavidR-Vortex** [OpenRadioss/OpenRadioss#1261]
Hello Radioss team,

When running LS-Dyna format models,

Could errors in starter arising from *DATABASE_BINARY_D3DRLF and similar be replaced with a "warning this output is ignored" type of message. 

Many thanks,
David

**Comment by sebastienVilleneuve** [comment]
Hi @DavidR-Vortex , I will take care of this.

Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
https://github.com/OpenRadioss/OpenRadioss/commit/340550436a9123e2ff8e1dcaa095a18e1b128c62

Regards,
Sébastien

**Comment by DavidR-Vortex** [comment]
Thanks @sebastienVilleneuve !
