### ISSUE TITLE
In /PROP/SOLID settings, combination of Itetra4 = 3 and Ismstr = 10 doesn't cause any warnning or error messages

### ISSUE THREAD

**Issue by wgm096350** [OpenRadioss/OpenRadioss#1271]
According to the Radioss Reference Guide, "Ismstr = 10 and 12 are not compatible with /TETRA4 with Itetra4 = 3.".  Thus, combination of  Itetra4 = 3 and Ismstr = 10 is not compatible and should be identified by starter_win64.exe which issuing an warning/error message. Howerver, no warning/error message is observed.
![image](https://user-images.githubusercontent.com/24369346/227079403-5db1d1dd-10d3-4275-bf22-4a11cdf16d73.png)
After callling the starter_win64.exe, the *.out file contains "PART ELEMENT/MATERIAL PARAMETER REVIEW:"
![image](https://user-images.githubusercontent.com/24369346/227080441-5eadde81-5491-4f68-a488-8777209d0a74.png)
In this REVIEW information, combination of Itetra4 = 3 and Ismstr = 10 is also allowed.

**Comment by wgm096350** [comment]
[kkkk_0000.zip](https://github.com/OpenRadioss/OpenRadioss/files/11046608/kkkk_0000.zip)

**Comment by Schwoertzig** [comment]
Hi @wgm096350 , thank you very much for reporting this. I am going to update the manual page in order to remove this comment. Itetra=4 was made compatible with Ismtr=10 and 12. So it is an expected situation which does not lead to a warning message. Best Regards.

**Comment by Schwoertzig** [comment]
@wgm096350, Manual page was updated. It will be released with version 2023. 
 Thank you again for this feedback.
