### ISSUE TITLE
Issue in LS-DYNA reader when reading *MAT_OGDEN_RUBBER

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1346]
**Describe the bug**
The LS-DYNA reader is not able to read *MAT_OGDEN_RUBBER_TITLE.

**To Reproduce**
Run the attached model
[ogden.k.gz](https://github.com/OpenRadioss/OpenRadioss/files/11185090/ogden.k.gz)

**Expected behavior**
The model should run.

**Output**
The error in ogden_0000.out:
![grafik](https://user-images.githubusercontent.com/80820850/230764364-a6ba401c-b2ea-47d7-99fd-046b48f15c7c.png)

**Desktop (please complete the following information):**
 - Version [1cd0db7b99f8ad04f7de58c8715076141ffb3662]
- Hardware [Linux: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration [double precision SMP]

**Additional context**
When replace the empty field "n" (CARD 1, field 4) with a "0", the job will be executed.

**Comment by sebastienVilleneuve** [comment]
Hi @SonSiont 

Solved with : d42b2da951c8229929bbac6a4b8220a89fad13dc

Thanks,
Sébastien
