### ISSUE TITLE
ANIM/SHELL/DENS

### ISSUE THREAD

**Issue by DavidR-Vortex** [OpenRadioss/OpenRadioss#1356]
Hello Radioss team,

When using ANIM/SHELL/DENS with the Toyota Camry example, an array is produced but contains only zero's.

Many thanks,
David

**Comment by vdavaze** [comment]
Hi, 

This issue was fixed in 9cadca8b98ceef672bb1ee51ceee15093c746cd9 (#1466). 

Thanks a lot. 

Valentin.
