### ISSUE TITLE
How to ouput strain of a truss element?

### ISSUE THREAD

**Issue by wgm096350** [OpenRadioss/OpenRadioss#1366]
Hello Radioss team,
The stress of a truss element could be outputed by the keyword /ANIM/TRUSS/. But this keyword seems not able to output the strain.
Is there an alternative way for strain output of a truss element?
Many thanks,

**Comment by MarianBulla** [comment]
Hello,
did you try this one: 

/ANIM/TRUS/EPSX

for the total strain output ?

Thanks and best regards,
Marian

**Comment by MarianBulla** [comment]
![image](https://github.com/OpenRadioss/OpenRadioss/assets/105412502/5f3264fd-4b91-4a47-bffd-ff932086df8c)
