### ISSUE TITLE
Is it possible to debug OpenRadioss in Visual Studio?

### ISSUE THREAD

**Issue by wgm096350** [OpenRadioss/OpenRadioss#1388]
Dear OpenRadioss Team,
I need to add new feature in OpenRadioss. When debugging ,how to set breakpoints and run code line by line?
best regards,
thanks

**Comment by OlivierWienholtz** [comment]
Hello,
Work is in progress on this topic. 
Indeed we are creating configuration files which will permits you to build Debug executables & set Breakpoints & co in Visual Studio....

Best Regards,
Olivier

**Comment by OlivierWienholtz** [comment]
Hello, 
We did  some adjustments on the Windows builds with commit ID 8843bbb35cf7b0fbe9e8af5c7197f2acb7db7ba7

In order to create the debugging symbol files .pdb
You will find in the HowTo  how to build OpenRadioss with Visual Studio.
A documentation how to use the Visual Studio Debugger is being written.

**Comment by OlivierWienholtz** [comment]
Some new comments : 
The Workflow how to build OpenRadioss is explained here:
https://github.com/OpenRadioss/OpenRadioss/blob/main/HOWTO.md#build-openradioss-with-visual-studio

The Workflow how to use the Debugger is maintained here
https://github.com/OpenRadioss/OpenRadioss/blob/main/doc/Visual_Studio_Debugger.md

**Comment by wgm096350** [comment]
> Some new comments : The Workflow how to build OpenRadioss is explained here: https://github.com/OpenRadioss/OpenRadioss/blob/main/HOWTO.md#build-openradioss-with-visual-studio
> 
> The Workflow how to use the Debugger is maintained here https://github.com/OpenRadioss/OpenRadioss/blob/main/doc/Visual_Studio_Debugger.md

Awesome

**Comment by OlivierWienholtz** [comment]
Hello, since you have started another thread. Lets discuss your problem in the other issue.
I propose we close this one, as I believe the functionality is available.
