### ISSUE TITLE
Support /RBE3 with solid elements

### ISSUE THREAD

**Issue by hyperkang** [OpenRadioss/OpenRadioss#1395]
**Is your feature request related to a problem? Please describe.**
The attached model has /RBE3 connecting nodes on solid elements.  The reference (dependent) node is applied with torque (moment along zz direction).  Such definition is valid in other solvers like Abaqus.  However OpenRadioss runs into error as follows:

```
ERROR ID :    845
** ERROR IN CONCENTRATED LOAD DEFINITION
DESCRIPTION :  
   -- CONCENTRATED LOAD ID: 1
   -- CONCENTRATED LOAD TITLE: 
   UNDEFINED CONCENTRATED LOAD DIRECTION ZZ
   NO ROTATIONAL DOF IN THE INPUT DECK
```

**Describe the solution you'd like**
I expect OpenRadioss support such definition (/RBE3 with solid elements). 

[rbe3_solid.zip](https://github.com/OpenRadioss/OpenRadioss/files/11315349/rbe3_solid.zip)

**Comment by qiangRadioss** [comment]
Hi Kang,

how are you going? glad to see you here.
I guess the issue comes from the fact that we impose a moment on the node which has no dof of rotation.
You said Abaqus can do that, do you know Abaqus does it in any case or only in case where the node is dependent node of RBE3?
in waiting for OpenRadioss fixing this, the workaround is to create a spring w/ rotational dof (e.g. type8) and connecting the spring with this dependent node (that will create rotational dof for this node).

thanks.

Qiang.

**Comment by qiangRadioss** [comment]
Kang,

For the workaround, you should change your /RBE3 to:
# Node_IDrTrarot_ref     N_set   I_modif
      1001   111 111         1
                1.00   111 000                   5

**Comment by emestres** [comment]
Hi,
Here is a small example with the spring element as workaround.
Thanks,
[sample_model.zip](https://github.com/OpenRadioss/OpenRadioss/files/11453417/sample_model.zip)

**Comment by qiangRadioss** [comment]
issue fixed with 7e2e0cc4538beb040abe271676e7ae9fca6a70ef

Qiang.

**Comment by hyperkang** [comment]
> Hi Kang,
> 
> how are you going? glad to see you here. I guess the issue comes from the fact that we impose a moment on the node which has no dof of rotation. You said Abaqus can do that, do you know Abaqus does it in any case or only in case where the node is dependent node of RBE3? in waiting for OpenRadioss fixing this, the workaround is to create a spring w/ rotational dof (e.g. type8) and connecting the spring with this dependent node (that will create rotational dof for this node).
> 
> thanks.
> 
> Qiang.

Hi Qiang,

It is amazing to meet you here.  :)

As far as I know, it is common to apply load on the "dependent node" of RBE3. 

It looks you have already made a fix.   I will give a try.

Kang

**Comment by laurent-altr** [comment]
This issue should be fixed now. Feel free to reopen it if needed.
