### ISSUE TITLE
Support cylindrical coordinate system(/SKEW) for defining composite layer along the circular direction

### ISSUE THREAD

**Issue by hyperkang** [OpenRadioss/OpenRadioss#1401]
**Is your feature request related to a problem? Please describe.**
I have a structure with composite ribs (yellow component in below image) along the circular direction.  

<img width="775" alt="composite_orientation" src="https://user-images.githubusercontent.com/1835678/234483970-6a3ed208-4b99-4623-83ef-8bca266769d7.png">

**/PROP/TYPE11(SH_SANDW)** provides following options to define the layer direction, however it looks none of them could define the layer orientation along the circular direction.  Ip=20(defining reference vector V by node N1 and N2) might work, but it is too tricky for the modeling.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/1835678/234484411-6d3477dc-c975-4907-bcbf-60635fb2669e.png">

**Describe the solution you'd like**
Support cylindrical coordinate system(/SKEW) for defining composite layer along the circular direction.

**Comment by DimaFokin** [comment]
Dear HyperKang

it is possible with regular /PROP/TYPE11. Please find example and explanations. 

Let me know if you have further questions or comments

Regards Dima


[230511_Cylindrical_Composite.zip](https://github.com/OpenRadioss/OpenRadioss/files/11453307/230511_Cylindrical_Composite.zip)

**Comment by DimaFokin** [comment]
Hallo Kang, 
thank you for explanations. I confirm that this case can not be reproduced in RADIOSS now. I created a ticket for 2023.1 to implement a new flag IP=24 which sets material direction along radial direction of cylindrical coordinate system

Thanks a lot Dima

**Comment by hyperkang** [comment]
> Hallo Kang, thank you for explanations. I confirm that this case can not be reproduced in RADIOSS now. I created a ticket for developer to implement a new flag IP=24 which sets material direction along radial direction of cylindrical coordinate system
> 
> Thanks a lot Dima

Hi Dima,

Any progress on this request?  Can you please share the ticket you created?

BTW, besides /PROP/TYPE11, we would need cylindrical system for /PROP/TYPE9 as well.   Shall I create another ticket?

Thanks,
Kang

**Comment by DimaFokin** [comment]
Hallo Kang,

[JIRA] (RD-14894) /PROP/TYPE11, TYPE51: implement definition of material direction in cylindrical coordinate system

It is planned for all orthotropic properties including TYPE9

I see that the ticket is still under development. I will push it for 2024

Thanks and best Regards Dima

Von: Kang Zhao ***@***.***>
Gesendet: Freitag, 8. Dezember 2023 11:13
An: OpenRadioss/OpenRadioss ***@***.***>
Cc: Dima Fokin ***@***.***>; Comment ***@***.***>
Betreff: [EXTERNAL] Re: [OpenRadioss/OpenRadioss] Support cylindrical coordinate system(/SKEW) for defining composite layer along the circular direction (Issue #1401)


CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hallo Kang, thank you for explanations. I confirm that this case can not be reproduced in RADIOSS now. I created a ticket for developer to implement a new flag IP=24 which sets material direction along radial direction of cylindrical coordinate system

Thanks a lot Dima

Hi Dima,

Any progress on this request? Can you please share the ticket you created?

BTW, besides /PROP/TYPE11, we would need cylindrical system for /PROP/TYPE9 as well. Shall I create another ticket?

Thanks,
Kang

-

**Comment by qiangRadioss** [comment]
Hi Kang
i've done this devlp. (IP=25) in OpenRadioss see fa604428a02f323d433a353b3c35d9030933590e
You can try now (i was waiting Dima for the validation), for the moment i used N1 of shell (4N or3N) as element position for cylindrical coordinate system compute (z of skew_id is the symmetric axe) , if you think that's not precise enough, i can change it to element center (more changes have to be done).
let me know the feedback.

thanks.

Qiang.

**Comment by hyperkang** [comment]
> Hi Kang i've done this devlp. (IP=25) in OpenRadioss see [fa60442](https://github.com/OpenRadioss/OpenRadioss/commit/fa604428a02f323d433a353b3c35d9030933590e) You can try now (i was waiting Dima for the validation), for the moment i used N1 of shell (4N or3N) as element position for cylindrical coordinate system compute (z of skew_id is the symmetric axe) , if you think that's not precise enough, i can change it to element center (more changes have to be done). let me know the feedback.
> 
> thanks.
> 
> Qiang.

Hi Qiang,

Sorry for the late response.  

It's great to see this feature.  We will give a try and come back to you soon.

Thanks,
Kang

**Comment by qiangRadioss** [comment]
Hi Kang
just let you know, i've also made a small change after Dima's response, that element center is used for orthotropic direction compute from b091a3b0050ef74fcfd6f2073367665b0fa6da7a.
Qiang.

**Comment by hyperkang** [comment]
> Hi Kang just let you know, i've also made a small change after Dima's response, that element center is used for orthotropic direction compute from [b091a3b](https://github.com/OpenRadioss/OpenRadioss/commit/b091a3b0050ef74fcfd6f2073367665b0fa6da7a). Qiang.

Hi Qiang,

Can you please share the updated document about the new option IP=25, and an example input deck? 

Thanks,
Kang

**Comment by qiangRadioss** [comment]
Hi Kang,

here you are.
Qiang.
[RD_14894_ip25.zip](https://github.com/OpenRadioss/OpenRadioss/files/14376298/RD_14894_ip25.zip)

**Comment by hyperkang** [comment]
> Hi Kang,
> 
> here you are (test example from you, i guess) Qiang. [RD_14894_ip25.zip](https://github.com/OpenRadioss/OpenRadioss/files/14376298/RD_14894_ip25.zip)

Hi Qiang,

Thanks for the files.

Is option IP=25 available for /PROP/TYPE11 as well?

Kang

**Comment by qiangRadioss** [comment]
available for TYPE9, 10, 11, 16, 17, 51, STACK

**Comment by elequiniou** [comment]
I propose to close this issue, please feel free to reopen in case of further need; Thanks!
