### ISSUE TITLE
Breakpoints in radioss.F can't be hit

### ISSUE THREAD

**Issue by wgm096350** [OpenRadioss/OpenRadioss#1437]
Dear OpenrrRadioss Team,
According to the instructions in this link “https://github.com/OpenRadioss/OpenRadioss/blob/main/doc/Visual_Studio_Debugger.md”, I have successfully implemented OpenRadioss breakpoint debugging, but only some of the breakpoints can be hit. Take source file radioss.F as an example, only the breakpoint on line 28 can be hit, the breakpoint on lines 30 and 32 will not be hit, Visual Studio prompts "The Breakpoint will not currently be hit." No executable code of the debugger's target code type is associated with this line. Possible Causes include: conditional compilation, compiler optimization, or the target architecture of this line is not supported by the current debugger code type.” What's going on?
Best regards,
![断点无法命中](https://user-images.githubusercontent.com/24369346/236171741-ced0f105-394a-4fc9-a8a8-b38bc87704c2.png)

**Comment by OlivierWienholtz** [comment]
Hello,
It is likely the .pdb symbol file was not loaded. Pls check on the bottom left "Output tab" of your debug session : 
if the symbols are loaded.


![debug_symbols](https://user-images.githubusercontent.com/98882516/236197654-c3bb4ce4-ff02-489a-b22c-72bb195a65cf.png)

If not : have a look at [Tools][Option][Debugging][Symbols] if the directory set here is correct

**Comment by OlivierWienholtz** [comment]
Just to let you know, I found an issue in the build flags which causes this.
I'll send the fix in GitHub next week.

**Comment by wgm096350** [comment]
> Just to let you know, I found an issue in the build flags for debug which causes this. I'll send the fix in GitHub next week.

That‘s exciting!

**Comment by laurent-altr** [comment]
This issue seems to be resolved. I am closing it. 
Feel free to re-open it if needed.
