### ISSUE TITLE
TH of springs with mat SPR_SEATBELT gives unexpected results.

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1505]
**Describe the bug**
The output of the elements with /MAT/LAW114 (SPR_SEATBELT) report with /TH/SPRING/ not the expected values.

**To Reproduce**
Run the attached job.

**Expected behaviour**
The forces in the belt element should be as in the arms of the slipring.

**Output**
The slipring forces:
![slipringforce](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/d756d9bd-9257-4aea-8d0b-2fba219f1fb5)
The seatbelt forces:
![beltforce](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/ffe8420e-1e8e-4042-a659-f0ae0ff267f2)
The reported element numbers:
![numbers](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/2674c6f0-4329-408d-ac9a-4761c294a7bf)
The archive of the pictures and the RADIOSS file.
[belt1D.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/11564133/belt1D.tar.gz)
**Desktop (please complete the following information):**
 - Version [7394284b8e626914b1cf4de9764c2ba8f03a85d4]
- Hardware [Linux; Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration [double precision SMP, 4 threads]

**Additional context**

**Comment by sebastienVilleneuve** [comment]
Correction ongoing 
https://github.com/OpenRadioss/OpenRadioss/pull/1539

Regards,
Sébastien
