### ISSUE TITLE
Spring orientation with LAW108 is not correct.

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1564]
**Describe the bug**
Spring elements with LAW108 is not accepting the local coordinate system.
Element 97 should have an X-Force of 0.5 instead of 500.

**To Reproduce**
Run bushing1M_0000.rad and evaluate the spring force of element 97 or the forces at the boundaries.

**Expected behaviour**
The results should be similar as with SPR_MAT which is in bushing1P_0000.rad .

**Output**
The attached archive contain the input files.
[springdir.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/11708168/springdir.tar.gz)

**Desktop (please complete the following information):**
 - Version [a28a16fa3538ef65d7a8db16971304ac6c5dea68]
- Hardware [Linux; Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration [double precision one core]

**Additional context**
The springs are hard in compression and soft in tension and should be used for bush / bearing connections.
A number of attempts with different local orientations have not been successful.

**Comment by SonSiont** [comment]
Hi,
I had the problem with an LS-DYNA file. A cutting out of my model which was based on the NHTSA iss2023 model is here:
[bushing.k.gz](https://github.com/OpenRadioss/OpenRadioss/files/11718564/bushing.k.gz) , 
![bushing](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/40420fa9-deca-464d-b527-bb3a2323fb02)
Maybe I change the question a bit: What can I do to make the LS-DYNA file running as I expect?
In the meantime I look into your suggestion.
best regards

**Comment by SonSiont** [comment]
Hi,
you are right with SCOOR I have not filled in the value.
The include solution looks promising. My job produce results:
![vm](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/5e0dd546-b1d8-4bf3-b7c0-1c4573529ea0) ,
![spiderf](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/f3cbf8ff-6d12-4a17-be7e-24b3617191b6) .
I am not able to postprocess springs with something like  /ANIM/SPRING/FORC with paraview while beams are working. Do you have an hint how to do it?
best regards

**Comment by PaulAltair** [comment]
Yes, it seems the /ANIM/SPRING/FORC output is not coming across in vtk conversion (it is there in the original Annn files) I guess it needs to be added to the vtk conversion tool, I'll ask!

**Comment by sebastienVilleneuve** [comment]
@SonSiont 

I'm working to correct this .
We will let you know soon , but I found a bug .

Regards,
Sébastien

**Comment by sebastienVilleneuve** [comment]
@SonSiont 
Merged

33cce08b81ce028a9aa9c443043675b000e6de9f

Sébastien

**Comment by SonSiont** [comment]
Thanks,
it works well:
![spider](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/f6f6b2ea-a882-41c6-b1ff-af1cd3d9c982)
![spidervm](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/6dff093a-2216-4b16-89d0-ace06fc673c2)
Now I can highlight the difference between a rigid spider and the spring solution. In the picture above the tear off is visible.

I struggle a bit with the *INCLUDE_RADIOSS with the pilot node in RADIOSS for rigids while these are not in LS-DYNA but I try to handle it.

**Comment by SonSiont** [comment]
When an rigid body is translated to RADIOSS, the pilot node is a new node with arbitrary number. When apply a load to it, the pilot node should be used for the load. At the moment it seems to be that I can put the load alternative to an extra_node.

**Comment by PaulAltair** [comment]
If the load input on the Rigid is valid for Dyna then it should also work after translation, the main node of the Rbody should be created automatically, if you have a use case where it isn't working as expected can you share more details?

**Comment by PaulAltair** [comment]
Recent update, means MAT74 springs are now run in OpenRadioss as LAW113 instead of LAW108, should mean orientation is correct now more times by default when using .k input

**Comment by elequiniou** [comment]
I propose to close this issue as there is no more feedback after the correct in the code. Thanks!
