### ISSUE TITLE
Compiler flag bug -Werror=do-subscript: no option -Wdo-subscript

### ISSUE THREAD

**Issue by Fonotec** [OpenRadioss/OpenRadioss#1659]
**Describe the bug**
Bug caused by compiler flags. -Werror=do-subscript: no option -Wdo-subscript

**To Reproduce**
I followed the description on how to compile the code:
cd OpenRadioss/starter
 ./build_script.sh -arch=linux64_gf

**Expected behavior**
I expect the code to compile without problem.

**Output**
```
 Build OpenRadioss Starter 
 --------------------------
 Build Arguments :
 arch =                 :  linux64_gf
 precision =            :  dp
 debug =                :  0
 static_link =          :  0
...
...
...
-- Build files have been written to: /<user-directory>/Documents/OpenRadioss2/OpenRadioss/starter/cbuild_linux64_gf
[  0%] Generating CMakeFiles/includes_starter_linux64_gf/__foo.inc, CMakeFiles/includes_starter_linux64_gf/build_info.inc

('Create:', '/<user-directory>/Documents/OpenRadioss2/OpenRadioss/starter/cbuild_linux64_gf/CMakeFiles/includes_starter_linux64_gf/build_info.inc')

Scanning dependencies of target starter_linux64_gf
[  0%] Building Fortran object CMakeFiles/starter_linux64_gf.dir/share/message_module/inter_ancmsg_mod.F.o
f951: Error: -Werror=do-subscript: no option -Wdo-subscript
make[2]: *** [CMakeFiles/starter_linux64_gf.dir/build.make:1440: CMakeFiles/starter_linux64_gf.dir/share/message_module/inter_ancmsg_mod.F.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/starter_linux64_gf.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Desktop (please complete the following information):**
 - Version [latest-20230703]
- Hardware [Intel(R) Xeon(R) Gold 6234 CPU @ 3.30GHz]
- Configuration [not applicable]

**Comment by OlivierWienholtz** [comment]
Hello, 
One Question : which compiler do you use ?

**Comment by Fonotec** [comment]
Hello Olivier,
I use gfortran: GNU Fortran (SUSE Linux) 7.5.0.

**Comment by OlivierWienholtz** [comment]
Hi GNU Fortran 7.5 is too old for OpenRadioss. You'll encounter other compilation issues.
We recommend to use Devtoolset-11 which is the compiler we use to build the binaries. 
Can you install this compiler on your system ? 

Best Regards,
Olivier W.

**Comment by Fonotec** [comment]
Hi Olivier, 
Thanks for the information, I requested our IT department to install a more recent version of gfortran. They will install gcc12-fortran on our system later today, that is a gfortran version newer than devtoolset-11. I will let you know if it works with this newer version later today.
Best regards,
Folkert

**Comment by OlivierWienholtz** [comment]
Hi, 
gfortran compiler behave changes often between 2 versions, 
We did some adjustments for gfortran 12.
I recommend that you update your fork/clone with latest version of OpenRadioss main.

Best Regards,
Olivier W.

**Comment by Fonotec** [comment]
Hi Olivier,
Today our IT department finished installing the compiler. However, there is still an issue. There is different behaviour between using git clone and downloading the zip file on the release page of github (i.e. https://github.com/OpenRadioss/OpenRadioss/releases). Firstly, for downloading from the release page of github everything is working, so that is good news! However, for me it is unexpected that this works but the version I download/clone using git is not working.

In the case of git clone, I am still unable to compile the code successfully. Namely, for the starter I get the error:
```[ 99%] Building CXX object CMakeFiles/starter_linux64_gf.dir/source/system/c_hash_table.cpp.o
[100%] Linking Fortran executable starter_linux64_gf
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld:/<userdirectory>/Documents/OpenRadioss2/OpenRadioss/starter/../extlib/metis/linux64/libmetis_linux64_gcc.a: file format not recognized; treating as linker script
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld:/<userdirectory>/Documents/OpenRadioss2/OpenRadioss/starter/../extlib/metis/linux64/libmetis_linux64_gcc.a:1: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/starter_linux64_gf.dir/build.make:30759: starter_linux64_gf] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/starter_linux64_gf.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I think in this case something goes wrong with linking metis with openradioss.

In the case of the engine, I am also unable to compile the code and it is complaining about H3D:
```
/<userdirectory>/Documents/OpenRadioss2/OpenRadioss/engine/source/output/h3d/h3d_build_cpp/h3d_dl.c:1393:66: error: unknown type name ‘H3D_ID’
 1393 |  bool Hyper3DDatasetDoubleWriteWithSystem(H3DFileInfo* h3d_file, H3D_ID id,
      |                                                                  ^~~~~~
/<userdirectory>/Documents/OpenRadioss2/OpenRadioss/engine/source/output/h3d/h3d_build_cpp/h3d_dl.c:1394:32: error: unknown type name ‘H3D_ID’
 1394 |            const double* data, H3D_ID sys_id, H3D_ANALYSIS_SYSTEM system_flag)
      |                                ^~~~~~
/<userdirectory>/Documents/OpenRadioss2/OpenRadioss/engine/source/output/h3d/h3d_build_cpp/h3d_dl.c:1394:47: error: unknown type name ‘H3D_ANALYSIS_SYSTEM’
 1394 |            const double* data, H3D_ID sys_id, H3D_ANALYSIS_SYSTEM system_flag)
      |                                               ^~~~~~~~~~~~~~~~~~~
/<userdirectory>/Documents/OpenRadioss2/OpenRadioss/engine/source/output/h3d/h3d_build_cpp/h3d_dl.c:1400:25: error: unknown type name ‘H3DFileInfo’
 1400 |  bool Hyper3DDatasetEnd(H3DFileInfo* h3d_file)
      |                         ^~~~~~~~~~~
make[2]: *** [CMakeFiles/engine_linux64_gf.dir/build.make:42293: CMakeFiles/engine_linux64_gf.dir/source/output/h3d/h3d_build_cpp/h3d_dl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/engine_linux64_gf.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Best regards,
Folkert

**Comment by OlivierWienholtz** [comment]
Hi Folkert,

Starter & Engine are the same problem,
Those libraries  and include files are in a directory which is managed by LFS system. 

You need to install git-lfs on your Linux system 
& initialize it one installed :
git lfs install

After this you'll have to re-clone your local git repository, as the current one has empty library files.
( you can check extlib/hm_reader/linux64/libhm_reader_linux64.so...)

Pls let me know if you have still problems after installing git-lfs...

Best regards,
Olivier W.

**Comment by Fonotec** [comment]
Hi Olivier,
I can confirm that it works now, I will close the issue.
Cheers,
Folkert
