### ISSUE TITLE
How to change path in engine

### ISSUE THREAD

**Issue by julio-design** [OpenRadioss/OpenRadioss#1673]
The compilation of starter and engine turned out OK, so I tried to run some examples, and the starter ran correctly. However, when I tried ` engine_linux64_gf -i Bumper_Beam_AP_meshed_0001.rad`, I get the following:

```
 *** ERROR INPUT FILE: CANNOT CREATE TEMP FILE : /tmpBumper_Beam_AP_meshed_646_localhost.example.org !

MESSAGE ID :        144

 ** ERROR: INPUT FILE Bumper_Beam_AP_meshed_0001.rad NOT FOUND


     ERROR TERMINATION
```

The example is placed at the `/tmp` directory, so it should be `/tmp/file`, no `/tmpfile`. And I don't know why the hostname is paced also in the file.

**Comment by PaulAltair** [comment]
Where are you are running the engine from relative to the input files?

e.g. I am in folder with the example model and I run as follows
```
/home/psharp/OpenRadioss/OpenRadioss-PaulTesting/exec/starter_linux64_gf -i Bumper_Beam_AP_meshed_0000.rad -np 1 -nt 4
/home/psharp/OpenRadioss/OpenRadioss-PaulTesting/exec/engine_linux64_gf -i Bumper_Beam_AP_meshed_0001.rad -nt 4
```
you can try using my gui scripts, see if that makes life easier? [Gui Scripts, confluence](https://openradioss.atlassian.net/wiki/spaces/OPENRADIOSS/pages/45252609/python+tk+guis+for+job+submission+anim-vtk+conversion+and+T01-csv+conversion)

**Comment by OlivierWienholtz** [comment]
Hello,
can you pls share the engine command line you are using ?
And the contents of TMP, TMPDIR & TEMP environment variables ? 

Thank you

**Comment by julio-design** [comment]
> Where are you are running the engine from relative to the input files?

I exported a path: `PATH="$OPENRADIOSS_PATH/exec":$PATH; export PATH` to just run e.g., `starter_linux64_gf` or `engine_linux64_gf`. However, I run from absolute path `/usr/src/OpenRadioss/exec/engine_linux64_gf -i Bumper_Beam_AP_meshed_0000.rad`, but still isn't working.

> Hello, can you pls share the engine command line you are using ? And the contents of TMP, TMPDIR & TEMP environment variables ?

I don't have declared variables for TMP, TMPDIR or TEMP. But that is not the problem. I moved the `.rad` files to $HOME and the output is the same:

```
$ engine_linux64_gf -i Bumper_Beam_AP_meshed_0001.rad 
 *** ERROR INPUT FILE: CANNOT CREATE TEMP FILE : /home/julioBumper_Beam_AP_meshed_12531_art.jcrcx.xyz ! 
MESSAGE ID :        144 
 ** ERROR: INPUT FILE Bumper_Beam_AP_meshed_0001.rad NOT FOUND 
     ERROR TERMINATION 
```

**Comment by PaulAltair** [comment]
Engine submission should be calling your _0001.rad not your _0000.rad (or is that just a typo?)

**Comment by julio-design** [comment]
> Engine submission should be calling your _0001.rad not your _0000.rad (or is that just a typo?)

It's just a typo sorry.

I declared the variables in my `.zshrc`:

```
## OpenRadioss
export OPENRADIOSS_PATH=/usr/src/OpenRadioss
PATH="$OPENRADIOSS_PATH/exec":$PATH; export PATH
export RAD_CFG_PATH=$OPENRADIOSS_PATH/hm_cfg_files
export RAD_H3D_PATH=$OPENRADIOSS_PATH/extlib/h3d/lib/linux64
export OMP_STACKSIZE=400m
export LD_LIBRARY_PATH=$OPENRADIOSS_PATH/extlib/hm_reader/linux64/:$LD_LIBRARY_PATH
```

I tried the script, but I got the following error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/tmp/linux_scripts/RunJobScriptLin.py", line 16, in run_script
    subprocess.call(['./runORjob.sh', arg1, arg2, arg3, arg4])
  File "/usr/lib64/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './runORjob.sh'
```

**Comment by PaulAltair** [comment]
ok, the .sh I wrote for linux submission are in bash, some commands are different, so it would be necessary to update some commands for zsh
I did a quick modification (I could not test, so hopefully it is ok!) here: (new version of the script and python)
[linux_scripts_zshell.zip](https://github.com/OpenRadioss/OpenRadioss/files/11968638/linux_scripts_zshell.zip)
for permissions, make sure the scripts are set executable (chmod 777) before trying to use them
I wonder if zshell is causing some of the other issues you see too?

**Comment by PaulAltair** [comment]
> ok, the .sh I wrote for linux submission are in bash, some commands are different, so it would be necessary to update some commands for zsh I did a quick modification (I could not test, so hopefully it is ok!) here: (new version of the script and python) [linux_scripts_zshell.zip](https://github.com/OpenRadioss/OpenRadioss/files/11968638/linux_scripts_zshell.zip) for permissions, make sure the scripts are set executable (chmod 777) before trying to use them Furthermore pyhton/tk is a prerequisite, for using the gui tool, not all distros have it by default, under a debian based release you can install with apt, I am not so familiar with package tools in slackware, but assume there is something similar? `sudo apt-get install python3-tk` I wonder if zshell is causing some of the other issues you see too?

Actually, sorry, this won't work... I just tried installing zsh, and running from there I get same errors as you, mostly, even with updated scripts... and I do not think I can get the gui to work in it (without major rewrite) as zsh does not support stack manipulation (pushd, popd) like bash, can you install bash and try in bash?

**Comment by julio-design** [comment]
I made the script executable, and now it runs as expected, however when the script runs the `engine_linux64_gf` on the `file_0001.rad` it still gives the same error as before.

**Comment by julio-design** [comment]
I tried to recompile `engine/build_script.sh` and I think is not going all the way through. 

```
 /usr/src/OpenRadioss/engine % ./build_script.sh -arch=linux64_gf
 Build OpenRadioss Engine 
 -------------------------
 Build Arguments :
 arch =                 :  linux64_gf
 mpi =                  :  SMP Only
 mpi_os =               :  0
 precision =            :  dp
 debug =                :  0
 static_link =          : 
 
 #threads for Makefile :  1
 
 
 -- Remove executable in build_script 
 -- Remove executable in exec 
 
-- Loading linux64_gf settings
-- modules: /usr/src/OpenRadioss/engine/cbuild_linux64_gf/CMakeFiles/modules
-- Fortran Compiler: /usr/bin/gfortran
-- C Compiler: /usr/bin/gcc
-- CPP Compiler: /usr/bin/g++
-- Exec name: engine_linux64_gf 
-- MPI: smp 
-- MPI libraries :  
-- MPI include directory :  
-- Flags release:   
-- Precision: dp 
-- Runtime Static link :  
-- debug: 0 
-- Build_type : o
-- Configuring done (0.1s)
-- Generating done (0.4s)
-- Build files have been written to: /usr/src/OpenRadioss/engine/cbuild_linux64_gf
[  0%] Generating CMakeFiles/includes_engine_linux64_gf/__foo.inc, CMakeFiles/includes_engine_linux64_gf/build_info.inc

('Create:', '/usr/src/OpenRadioss/engine/cbuild_linux64_gf/CMakeFiles/includes_engine_linux64_gf/build_info.inc')

[  0%] Generating CMakeFiles/includes_engine_linux64_gf/__foo.inc, CMakeFiles/includes_engine_linux64_gf/build_info.inc

('Create:', '/usr/src/OpenRadioss/engine/cbuild_linux64_gf/CMakeFiles/includes_engine_linux64_gf/build_info.inc')

[  0%] Building Fortran object CMakeFiles/engine_linux64_gf.dir/source/engine/execargcheck.F.o
[  1%] Building Fortran object CMakeFiles/engine_linux64_gf.dir/source/engine/radioss2.F.o
[  1%] Building Fortran object CMakeFiles/engine_linux64_gf.dir/source/engine/radioss_title.F.o
[  1%] Building Fortran object CMakeFiles/engine_linux64_gf.dir/source/output/h3d/h3d_results/genh3d.F.o
[  2%] Linking Fortran executable engine_linux64_gf
[100%] Built target engine_linux64_gf
 
 -- Copy engine_linux64_gf in ../exec 
 ```

**Comment by PaulAltair** [comment]
No, that looks ok, if you didn't redownload source, then rebuilding/recompiling is pretty quick and your output looks typical I think

**Comment by PaulAltair** [comment]
Can you try making a copy of the engine executable to the run directory and running from there to see if you still get the same error

**Comment by julio-design** [comment]
Still not working...

I did the following:

```
$ sudo cp /usr/src/OpenRadioss/exec/engine_linux64_gf /tmp
$ cd /tmp
$ sudo chown <user> engine_linux64_gf
$ ./engine_linux64_gf -i Bumper_Beam_AP_meshed_0001.rad

 *** ERROR INPUT FILE: CANNOT CREATE TEMP FILE : /tmpBumper_Beam_AP_meshed_20086_art.jcrcx.xyz !

MESSAGE ID :        144

 ** ERROR: INPUT FILE Bumper_Beam_AP_meshed_0001.rad NOT FOUND


     ERROR TERMINATION
```

**Comment by PaulAltair** [comment]
I'm out of ideas, I've installed zsh on my linux vm, deliberately set envvars incorrectly, and even then everything is still working ok (in lubuntu), I'll speak to some people tomorrow!
![image](https://github.com/OpenRadioss/OpenRadioss/assets/98418895/7a4461fd-40bc-4b13-9f3f-b9dd359833ad)

**Comment by julio-design** [comment]
Now it works. I tried [this release](https://github.com/OpenRadioss/OpenRadioss/releases/tag/latest-20230706) with the exec binaries already compiled. Maybe there was an error during the compilation with the main branch. Sorry for the inconvenience.

**Comment by PaulAltair** [comment]
Ok, thanks for the feedback, if you just want to run OpenRadioss, then the binaries are an easier option, no need to apologise, solving problems if we can, where they arise, makes everyone's life easier in the long run!
