### ISSUE TITLE
Issue with /RETRACTOR/SPRING

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1681]
**Describe the bug**
The combination of the seat belt and the seat belt retractor responds with an incorrect force.

**To Reproduce**
Run the attached RADIOSS model and evaluate the belt length, slip and the forces.

**Expected behavior**
The images show the response when a displacement is applied:
![dispSlip](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/70a9959f-624e-4919-b3d3-4606485ce93a)
![forces](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/ede3a46e-bfee-497f-a7fb-b715f3ce6e0e)
The archive:
[retractor_issue.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/11969878/retractor_issue.tar.gz)

**Output**
The forces and the displacement:

The archive with the model:

**Desktop (please complete the following information):**
 - Version [1cb5bcbaaf240f0c2d9e2874dd0fa638c88e6e4d]
- Hardware [Linux; Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration [doble precision SMP with one core]

**Additional context**
In the archive is an octave script that evaluates the equilibrium points.
The sum of belt length and slip is equal to the displacement applied.
Minor Issue: When running the starter, /SENSOR/TIME expects an end time. This is not mentioned in the reference manual.

**Comment by PaulAltair** [comment]
Thanks for reporting: I am able to replicate, investigating further!

It seems peculiar to the particular combination of the RETRACTOR and LAW114 springs sequentially if I make some mods to connectivity, or 'stiffness' of the slip or of the springs then the behaviour is as expected... (but not what you need)

**Comment by bertrand-altair** [comment]
Correction done :
https://github.com/OpenRadioss/OpenRadioss/commit/45ef7d51002349d1b09bc54b4fe912fafc5eb413

There was a bug in retractor computation when then material of the seatblet is non linear.

Regards,
