### ISSUE TITLE
Confusing judgment conditions

### ISSUE THREAD

**Issue by ZhengZQ007** [OpenRadioss/OpenRadioss#1757]
The following IF conditions in /engine/source/interfaces/int24/i24for3.F, line 672, is somewhat confusing. Statements belong to ELSEIF(IVIS2==2)THEN seems never be executed. 

IF(IVIS2==0)THEN
ELSEIF(IVIS2==1.OR.IVIS2==2)THEN
ELSEIF(IVIS2==2)THEN
ELSEIF(IVIS2==3)THEN
ELSEIF(IVIS2==4)THEN
ELSEIF(IVIS2==5)THEN
ELSE
ENDIF

https://github.com/OpenRadioss/OpenRadioss/blob/325dc21e38367fbf2b542725d8de2dc9fc1c4c27/engine/source/interfaces/int24/i24for3.F#L672

**Comment by qiangRadioss** [comment]
yes you are right, block of IVIS==2 is useless, i'll remove it.
thanks.
Qiang.

**Comment by qiangRadioss** [comment]
done by PR b2abd109f8172e697dcde9c5668be1505e73a70a
Qiang

**Comment by MarianBulla** [comment]
Dear ZhengZQ007,
thank you very much in your interest in OpenRadioss and for pointing to that.
Also thank you, Qiang, solving it.

I will close this issue as it seems to be solved.

Thanks and best regards,
Marian
