### ISSUE TITLE
Shell element integration points (Lobatto vs Gaussian quadrature)

### ISSUE THREAD

**Issue by Fonotec** [OpenRadioss/OpenRadioss#1821]
We want to compare using Lobatto vs Gaussian integration schemes for shell elements. In LS-DYNA we did a test like this and we want to see what is the difference compared to LS-DYNA and OpenRadioss. I was wondering if this is possible to do in OpenRadioss? I also was wondering what the default shell element integration points are, in the theory manual it is written: "For shell elements, integration points through the thickness are almost Lobatto points." This seems to indicate that the code does not use exactly Lobatto? Or does it?

**Comment by MarianBulla** [comment]
Hi, 
Yes, for the classic shells, we use the Labatto integration scheme. The Gaussian one can be achieved by using the layered shell type 10 or 11. For the fully integraged elements, the in-plane distribution is according to the Gaussian distribution.
Hope it helps you ?
Thanks and best,
Marian

**Comment by Fonotec** [comment]
Hi Marian, 
Thanks for your quick reply, yes this helps!
Thanks,
Folkert
