### ISSUE TITLE
libraduser*.a is missing for User Subroutine compilation

### ISSUE THREAD

**Issue by BastiLoe** [OpenRadioss/OpenRadioss#2031]
I want to compile a user subroutine for Openradioss. This fails, as libraduser*.a is not present. In commercial Radioss, theses files are present in "userlib_sdk" dictionary. This is missing in Openradioss.

**Comment by BastiLoe** [comment]
Edit: I figured out I need to compile using "build_script.bash"

**Comment by MarianBulla** [comment]
Hi BastiLoe,
yes, you are right. We have put the user library stuff into the tools section: https://github.com/OpenRadioss/Tools
Currently, you can use it with Linux or you need cygwin, if you want to go with windows.
We are working on a windows native version, and I will create also a YouTube video for "how to do it", soon.
So, stay tuned for few days, please.
It will come :-)

Thanks and best regards,
Marian

**Comment by MarianBulla** [comment]
Hi, 
it is available, now :-)
Please have a look here: https://www.youtube.com/watch?v=Js_i7CnZty0

Hope it helps you ?

Thanks and best regards,
Marian
