### ISSUE TITLE
Forget to update SUBTRIA(I)=IT0(3,ITQ)?

### ISSUE THREAD

**Issue by ZhengZQ007** [OpenRadioss/OpenRadioss#2036]
![image](https://github.com/OpenRadioss/OpenRadioss/assets/74033106/46123028-c719-4c2e-8af0-de2527b58b23)

https://github.com/OpenRadioss/OpenRadioss/blob/34d9d57ed5ad655a579cd3f43e9876e34b09df2e/engine/source/interfaces/int24/i24dst3.F#L1143C22-L1143C22

**Comment by qiangRadioss** [comment]
thanks well Zheng for this find, i've done the correction (see #2038).

Qiang.

**Comment by qiangRadioss** [comment]
Hi ZhengZQ007

Could you share the test model which shown this issue?

thanks.

Qiang.

**Comment by ZhengZQ007** [comment]
> Hi ZhengZQ007
> 
> Could you share the test model which shown this issue?
> 
> thanks.
> 
> Qiang.

Hi Qiang

This issue was found when I try to understand the algorithm of interface type24, because I want to do some secondary developments with respect to the general contact interface #1731. Another issue about the potential wrong nodal normal compute of interface type24 was found similarly #1951. Thanks for your previous introduction on type24, which is very helpful for me.

Best Regards.

Zheng.
