### ISSUE TITLE
Improve efficiency by replacing the loop over all edges to labeled edges 

### ISSUE THREAD

**Issue by ZhengZQ007** [OpenRadioss/OpenRadioss#2054]
IXWORK is suppressed by removing internal edges which do not need to add fictive nodes. https://github.com/OpenRadioss/OpenRadioss/blob/8fbc4a0080bd94d8339d1664bd80c015432c5f3c/starter/source/interfaces/inter3d1/i24surfi.F#L1381

Thus, may the loop range over all edges (DO L=1,LL) be replaced by labeled edges (DO L=1,NL)?https://github.com/OpenRadioss/OpenRadioss/blob/8fbc4a0080bd94d8339d1664bd80c015432c5f3c/starter/source/interfaces/inter3d1/i24surfi.F#L1463 https://github.com/OpenRadioss/OpenRadioss/blob/8fbc4a0080bd94d8339d1664bd80c015432c5f3c/starter/source/interfaces/inter3d1/i24surfi.F#L1483

**Comment by qiangRadioss** [comment]
Right, thanks Zheng again, when we created this subroutine (I24EDGE2), Iedge had several different values as option, now only one value is used. then make sense to change Do I=1,LL to Do i=1,NL and some code cleaning, that i've done in #2065

Qiang.

**Comment by qiangRadioss** [comment]
i close this issue.
