### ISSUE TITLE
th_to_csv: Wrong variable in if statement

### ISSUE THREAD

**Issue by hdrz** [OpenRadioss/OpenRadioss#2208]
https://github.com/OpenRadioss/OpenRadioss/blob/5b47ed28927fcc64d20e3eaabfcbdc02f46b1aa6/tools/th_to_csv/src/th_to_csv.c#L357

https://github.com/OpenRadioss/OpenRadioss/blob/5b47ed28927fcc64d20e3eaabfcbdc02f46b1aa6/tools/th_to_csv/src/th_to_csv.c#L868

Should be NUMGEO instead of NUMMAT if I'm not mistaken.

**Comment by sebastienVilleneuve** [comment]
https://github.com/OpenRadioss/Tools/pull/9

Correction ongoing

**Comment by sebastienVilleneuve** [comment]
a16b51027d38941e59df787b12d820fc6d8d9839
