### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by albenstein** [OpenRadioss/OpenRadioss#2235]
**Describe the bug**
When compiling with cmake on starter folder, it gives error like attached file.
[openradioss_compile_error.txt](https://github.com/OpenRadioss/OpenRadioss/files/13902665/openradioss_compile_error.txt)

**To Reproduce**
cd starter
./build_script.sh -arch=linux64_gf -mpi=ompi

**Expected behavior**
starter can be compiled.

**Output**
[openradioss_compile_error.txt](https://github.com/OpenRadioss/OpenRadioss/files/13902665/openradioss_compile_error.txt)

**Desktop (please complete the following information):**
 - Version [latest from github]
- Hardware [2x Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz]

**Additional context**
cmake and python are installed with module environment.

**Comment by OlivierWienholtz** [comment]
Hi Aziz,

Some third party includes & libraries are stored in an LFS directory.
It looks like lfs is missing and the download of those file where not good.

I recommend to install git-lfs on yout Linux box and retry to clone OpenRadioss.

Hope it helps,
Olivier

**Comment by albenstein** [comment]
@OlivierWienholtz Thanks for your help, it's done like a charm.

**Comment by OlivierWienholtz** [comment]
Hi Aziz, 

Glad to hear that you could Solve your issue.

I wish you all best for 2024 ! 
Olivier
