### ISSUE TITLE
MAT_PLASTIC_KINEMATIC hardening parameter is not mapped properly?

### ISSUE THREAD

**Issue by SyazwanSamad** [OpenRadioss/OpenRadioss#2334]
**Describe the bug**
Openradioss mapped the LS-Dyna's MAT_PLASTIC_KINEMATIC to LAW44.
However, the keyword BETA in LS-Dyna is the exact opposite to OpenRadioss.
In LS-Dyna, if BETA is 0, then it is kinematic hardening, while 1 is isotropic hardening (refer figure below)
In LAW44, it is vice versa. However, the BETA value from LS-Dyna is directly translated to OpenRadioss, without any conversion.

![image](https://github.com/OpenRadioss/OpenRadioss/assets/113438036/e3be0eed-4aae-44f0-af77-191e3ad15863)

**To Reproduce**
Run the following attachment. Out file is included.
[ISOTROPIC_vs_KINEMATIC.zip](https://github.com/OpenRadioss/OpenRadioss/files/14241236/ISOTROPIC_vs_KINEMATIC.zip)

**Expected behavior**
1-BETA value is expected for LAW44's ISO-KINEMATIC HARDENNING (typo) FACTOR

**Output**
In example of the LS-Dyna model below, the material is defined with kinematic hardening. 
But it is converted to isotropic hardening in OpenRadioss
![image](https://github.com/OpenRadioss/OpenRadioss/assets/113438036/b2f06a6d-e0e1-4161-ae17-f958775e7278)

**Desktop (please complete the following information):**
 - Version: 7a679f2
- Hardware: Intel Xeon Gold
- Configuration: Win64. IntelMPI, run using 20CPU, 1 thread

**Comment by elequiniou** [comment]
Dear Syazwan, thanks a lot for reporting this issue, the dev team is on it and will update you when fixed.
Kind Regards,
Eric

**Comment by SyazwanSamad** [comment]
> Dear Syazwan, thanks a lot for reporting this issue, the dev team is on it and will update you when fixed. Kind Regards, Eric

Hi Eric. Thank you too for the feedback.
Regards
Syazwan

**Comment by sebastienVilleneuve** [comment]
@SyazwanSamad 
I let you restest with last OpenRadioss executables, Issue should be solved .

thanks,
Sébastien

**Comment by SyazwanSamad** [comment]
Hi @sebastienVilleneuve 
I have tested it using commit e6b02db, it works fine.
![image](https://github.com/OpenRadioss/OpenRadioss/assets/113438036/31872ed6-2d0c-4798-af3a-4a72ca97904c)

I will close this issue.
Thank you.
Regards,
Syazwan
