### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by ljhlml** [OpenRadioss/OpenRadioss#2371]
### Discussed in https://github.com/orgs/OpenRadioss/discussions/1449

<div type='discussions-op-text'>

<sup>Originally posted by **FGarelli** May  8, 2023</sup>
Hi, I'm trying to install Openradioss but I have this error when I start to install the starter pack:
![021b5f5ceac33a351b2f38075e89df0](https://github.com/OpenRadioss/OpenRadioss/assets/159683975/48b404f4-a0fa-491e-9277-246a70da1d22)

What should i do?
</div>

**Comment by ljhlml** [comment]
I am using version 2024.0.0.2 of oneAPI+VS2022

**Comment by OlivierWienholtz** [comment]
Hello,

We have identified issues with the Visual Studio OneAPI Plugin starting from 2024.0
Indeed the OneAPI binaries are no more found.

One Workaound is to load the OneAPI parameters prior to run Visual Studio.
In a batch script : 

call "c:\Program Files (x86)\Intel\oneAPI\setvars.bat"
devenv.exe

**Comment by ljhlml** [comment]
Thank you for your response.
Indeed, as you mentioned, calling Visual Studio in the cmd prompt resolved the issue. I followed the official video on YouTube to reinstall it, and encountered no errors.
Wishing you continued productivity and good health!
