### ISSUE TITLE
Spring element and wrong frequency

### ISSUE THREAD

**Issue by Fonotec** [OpenRadioss/OpenRadioss#2520]
**Describe the bug**
I made a model that consist out of two nodes with a spring between them, the spring element has a mass. One of the nodes is fixed in space, the other node has an impose force on it such that it starts oscillating. For a linear spring with a mass M, the effective mass is given by M/3. Using this effective mass, we can calculate the frequency as \omega= sqrt(3k/M). Furthermore, the complete evolution of the spring is given by:
X(t) = F_0 / k (THETA(t) - cos(\omega t)), where F_0 is the imposed force and THETA is the Heavyside step function.

When I do the simulation, I get the following plots:
 
[vertical_displacement_short.pdf](https://github.com/OpenRadioss/OpenRadioss/files/14976717/vertical_displacement_short.pdf)

[vertical_displacement.pdf](https://github.com/OpenRadioss/OpenRadioss/files/14976725/vertical_displacement.pdf)

[fft_spectrum.pdf](https://github.com/OpenRadioss/OpenRadioss/files/14976727/fft_spectrum.pdf)

**To Reproduce**
To reproduce the behaviour you can run the following .rad files:
https://filesender.surf.nl/?s=download&token=b66b2e19-88f0-4736-b8d8-64565a356abf

**Expected behavior**
The expected behaviour is that the spring element produces the correct frequency. 

**Desktop (please complete the following information):**
 - Version from 11 april 2023
- Hardware Intel(R) Xeon(R) Gold 6444Y
- Configuration SMP, 1 thread

**Comment by laurent-altr** [comment]
Thank you for bringing this issue to our attention.
Our developers will investigate this matter and keep you updated on our progress.

**Comment by bertrand-altair** [comment]
Hi Fonotec,
The theorical results you are referring to are when considering uniform distribution of mass along the spring. In Radioss mass of the spring is equally distributed on the 2 nodes. So in your case, in Radioss it's like having a ponctual mass (M/2) connected to a spring with negligible mass. This the is the reason why the natural frequency of the system is sqrt(2k/M) instead of sqrt(3k/M) and why it is 18% lower.
Regards,
Bertrand,

**Comment by laurent-altr** [comment]
Following Bertrand's response, I am closing this issue.
