### ISSUE TITLE
Failure using RETRACTOR and PRETENSION elements running with MPI.

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#2696]
**Describe the bug**
Dependent of the number of SMPD domains radioss fails when using RETRACTOR and PRETENSION elements.

**To Reproduce**
In the archive is the folder result3err. When running with three SMPD domains at least the locking status of one retractor is wrong and and the program terminates with "ERROR TERMINATION".

**Expected behaviour**
The programme should run like the run with four SMPD domains, as in the result4ok folder.

**Output**
![lock](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/abf8b004-3281-4ead-aa4a-c4a3ba7b3d74)

The archive contains the inputs and results of the failed run and the correct run.
[transfer.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/15446925/transfer.tar.gz)

**Desktop (please complete the following information):**
 - Version [3b8a1735260757ddab64a5e1898198a0a9131523]
- Hardware [Linux; Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration:
 NUMBER OF SPMD DOMAINS           3
 NUMBER OF THREADS PER DOMAIN     1
 NUMBER OF HMPP PROCESSES         3

**Additional context**
Error message from stdout/stderr:

free(): invalid next size (fast)

User or system abort detected (CTRL-C) !

     ERROR TERMINATION

Presumption:
    Individual elements are distributed across domains and are not linked correctly.

**Comment by laurent-altr** [comment]
Thank you for reporting this bug.

A bug is causing wrong TH output, and possible segmentation violation.
The fix will be available soon: #2698

Best regards, 
Laurent

**Comment by laurent-altr** [comment]
#2698 should fix this. 
Feel free to reopen this issue if needed.
