### ISSUE TITLE
Starter crashes when running using WSL

### ISSUE THREAD

**Issue by SyazwanSamad** [OpenRadioss/OpenRadioss#2729]
**Describe the bug**
Starter (gfortran) crash when it is executed in WSL. Starter compiled using the AOCC compiler also have the same error. 
However, it is able to run just fine in Windows compiled with IntelOne.

**To Reproduce**
Run the following model downloaded from CCSA:
https://www.ccsa.gmu.edu/models/2010-toyota-yaris/

**Output**
out file stopped halfway:
![image](https://github.com/OpenRadioss/OpenRadioss/assets/113438036/c3b0c4ea-d811-46a7-8a63-f2368fa382e8)

**Configuration**
 - Commit ID: aae1279
- HW: AMD Ryzen 7 5700G with Radeon Graphics (x86_64), 3792 MHz, 6876 MB RAM, 1924 MB swap
-  Number of OpenMP threads = 1, MPI tasks = 8

**Comment by laurent-altr** [comment]
Hi @SyazwanSamad, 
I have been able to run this model with WSL, built with AOCC4.2.
Nevertheless, it needed about 11GB of RAM to run the starter.

Thank you, 
Laurent

**Comment by SyazwanSamad** [comment]
@laurent-altr thank you for the feedback. My system only have 16GB of RAM so by default WSL only allows up to 8GB of RAM. I will try to increase the limit (if possible) and let you know the outcome.

**Comment by SyazwanSamad** [comment]
@laurent-altr after increasing the WSL memory to 12GB, the starter did not crash. Thank you for the suggestion, I will close this issue.
