### ISSUE TITLE
Is the ordering of the strains correct?

### ISSUE THREAD

**Issue by hdrz** [OpenRadioss/OpenRadioss#2775]
https://github.com/OpenRadioss/OpenRadioss/blob/4d8fbe490c9500fd3bc1d7fb2104f6f7ab6313c2/starter/source/output/th/hm_read_thgrou.F#L634

`EPSZX` comes before `EPSYZ`. I think it should be the other way around, but maybe I'm wrong?

Thanks!

**Comment by sebastienVilleneuve** [comment]
Hi @hdrz 

No issue with this : the way we fill the TH values is the same ( EPSZX comes before EPSYZ) .

Regards,
Sébastien
