### ISSUE TITLE
Secondary *MAT_ELASTIC LSDYNA card is mapped /MAT/LAW2

### ISSUE THREAD

**Issue by hitotech1221** [OpenRadioss/OpenRadioss#2826]
The secondary Ls-dyna card mid 2 is should be mapped to /MAT/LAW1. However mapped to /MAT/LAW2 (PLAS_JOHNS)

*MAT_ELASTIC_TITLE
PP
$#     mid        ro         e        pr        da        db  not used  not used
         1     900.06.000000E8      0.35       0.0       0.0         0         0
*MAT_ELASTIC_TITLE
steel
$#     mid        ro         e        pr        da        db  not used  not used
         2     100.02.05000E11       0.3       0.0       0.0         0         0

0001.out file is bellow.
*MAT_ELASTIC_TITLE (2)  steel
    is mapped to
/MAT/LAW2 (2)  steel

**Comment by sebastienVilleneuve** [comment]
Hi @hitotech1221 

I just double check on my machine  , I see MAT_ELASTIC_TITLE -> /MAT/LAW1 .

![image](https://github.com/user-attachments/assets/76cd9957-447c-493f-af00-bcbc34578ef3)


can you share your input deck ?

Thanks,
Sébastien

**Comment by hitotech1221** [comment]
Hi, @sebastienVilleneuve 

There are input & output files.

input lsdyna card
[solid.txt](https://github.com/user-attachments/files/16990629/solid.txt)
starter output
[solid_0000.out.log](https://github.com/user-attachments/files/16990631/solid_0000.out.log)

Thank you ,
Hitoshi

**Comment by sebastienVilleneuve** [comment]
Hi @hitotech1221 

Ok, I understand ,
This is a choice we've made in case SECTION_BEAM + MAT_ELASTIC

Regards,
Sébastien

**Comment by sebastienVilleneuve** [comment]
Hello,
I close the ticket .
@hitotech1221  : Feel free to reopen it if your issue is not solved.
