### ISSUE TITLE
export OMP_STACKSIZE=400m->M

### ISSUE THREAD

**Issue by jhgoebbert** [OpenRadioss/OpenRadioss#2995]
Hello everyone,

I just came across this lines `export OMP_STACKSIZE=400m` :
https://github.com/search?q=repo%3AOpenRadioss%2FOpenRadioss+OMP_STACKSIZE%3D&type=code

This must be `export OMP_STACKSIZE=400M` (with a capital `M`) or you will get the error message
` libgomp: Invalid value for environment variable OMP_STACKSIZE`

**Comment by jhgoebbert** [comment]
possibly not significant ... Sorry for the noise

**Comment by OlivierWienholtz** [comment]
Hello,

Thank you for this.
Interesting, I'll have a look in the documentation.

Btw:
There is an example at openmp.org with lower 'm' in OMP_STACKSIZE. 
https://www.openmp.org/spec-html/5.0/openmpse54.html

Best Regards,
Olivier
