### ISSUE TITLE
ERROR TRAPPED, ID 760

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#3020]
**Describe the bug**
RADIOSS starter stops with:
 ** ERROR TRAPPED : REPORT TO LISTING FILE

ERROR ID :    760

**To Reproduce**
Run RADIOSS with the attached file.

**Expected behavior**
Run through or give information.

**Output**
The input and output is attached.

**Desktop (please complete the following information):**
 - Version [67286ef8126a138aa84ac32129363d144e79fe7b]
- Hardware [Linux; Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration [number of OpenMP threads, and MPI tasks]
SMP with two threads.

**Additional context**
When using Igap=2 in interface TYPE25 rather than 3, the job is running.
The original, larger job was stopping in MPI but runs with SMP.
[trap.tar.gz](https://github.com/user-attachments/files/17161811/trap.tar.gz)

**Comment by SonSiont** [comment]
WARNING ID :   1079
** WARNING: CHECK TIED INTERFACE

Program received signal SIGSEGV, Segmentation fault.
0x000000000094ecfa in i25trivox_edg_ ()
Missing separate debuginfos, use: zypper install libcrypt1-debuginfo-4.4.15-150300.4.7.1.x86_64 libgcc_s1-gcc14-debuginfo-14.2.0+git10526-lp156.28.1.x86_64 libgfortran5-gcc14-debuginfo-14.2.0+git10526-lp156.28.1.x86_64 libgomp1-gcc14-debuginfo-14.2.0+git10526-lp156.28.1.x86_64 libquadmath0-gcc14-debuginfo-14.2.0+git10526-lp156.28.1.x86_64 libstdc++6-gcc14-debuginfo-14.2.0+git10526-lp156.28.1.x86_64 libuuid1-debuginfo-2.39.3-150600.4.12.2.x86_64
(gdb) back
#0  0x000000000094ecfa in i25trivox_edg_ ()
#1  0x000000000092ccc5 in i25buce_edg_ ()
#2  0x000000000098a697 in inint3_ ()
#3  0x00000000009a9cc0 in inintr_ ()
#4  0x0000000000f8d1ca in lectur_ ()
#5  0x0000000000fe6ecf in starter0_ ()
#6  0x000000000046fcc8 in main ()
(gdb) quit

**Comment by laurent-altr** [comment]
Hello @SonSiont , 
I have made a fix yesterday in #3027, 
Could you retry with the latest version?

Thank you, 
Laurent
