### ISSUE TITLE
No displacement for PRESCRIBE_BOUNDARY_MOTION (LS-Dyna file)

### ISSUE THREAD

**Issue by okkarkyaw122** [OpenRadioss/OpenRadioss#3124]
**Describe the bug**
I used VAD=0 (velocity) for a three point bending test. But the solver doesn't recognize it. 

**To Reproduce**
Please run the file attached.
[3PB.k.zip](https://github.com/user-attachments/files/17655340/3PB.k.zip)
This file run perfectly fine in LS dyna.

**Expected behavior**
The indenter should moves in Z direction

**Output**
I attached the k file for your reference.

**How I solved**
I changed VAD=2(displacement) it works. But I think some people would still prefer to use the velosity which is why I reported. 

**Desktop (please complete the following information):**
 - Version commit ID [d17692d]
- Hardware [Ryzen 7700]
- Configuration [8, 0]

**Comment by sebastienVilleneuve** [comment]
Hi ,

Not able to open the attached file

Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
Hi @okkarkyaw122 

Issue occurs when VAD field is empty
Can you check putting vad = 0 ? ( on my side I see an imposed velocity)

![image](https://github.com/user-attachments/assets/ef443ab6-7915-48cf-83ba-d2e34f5a8543)

Regards,
Sébastien

Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
Hi @okkarkyaw122 

Correction ongoing .

Regards.

**Comment by okkarkyaw122** [comment]
<img width="1164" alt="image" src="https://github.com/user-attachments/assets/279c5a3a-09f9-4b2e-93c1-2481508e6cc7">
For VAD = 0 it is velocity for rigid body and nodes.  I will edit the key word file manually and check it again. Thank you.

**Comment by okkarkyaw122** [comment]
Hello it works when I put vad=0 manually. It seems like the problem is with the LS prepost not being able to write down the number 0.

**Comment by okkarkyaw122** [comment]
Thank you so much for your kind support

**Comment by sebastienVilleneuve** [comment]
@okkarkyaw122 

corrected with f01f6d98edf8d6d2e57cb09ed739ca373c233fbb

Regards,
Sébastien
