### ISSUE TITLE
OpenRadioss build with OpenMPI on UBUNTU 20.04.4 LTS fails

### ISSUE THREAD

**Issue by MarianBulla** [OpenRadioss/OpenRadioss#385]
**Describe the bug**
During building of OpenRadioss engine, an ERROR occures at the end of the compilation process, when adding OpenMPI.

**To Reproduce**
Using this command to start the building process:
./build_script.sh -arch=linux64_gf -mpi=ompi -nt=1

**Expected behavior**
The compiler should finish creating an executable without any error.

**Output**
Screenshot add to this Bug report.

**Desktop (please complete the following information):**
 - Windows10 / WSL Ubuntu 20.04.4 LTS  
 - Intel 7 CPU laptop
 - (see above **To Reproduce**)

![2022-09-04_20h56_24](https://user-images.githubusercontent.com/105412502/188600641-680b621a-1f91-46b0-b5a6-94d3625bb9a8.png)

**Additional context**
Without OpenMPI engine compiles correctly and executable runs fine.

**Comment by OlivierWienholtz** [comment]
This is fixed with 
commit id : 7e250765df76abc57cf7866948315f98d02e83f9

**Comment by MarianBulla** [comment]
The fix is working well. Building executables worked without any issues, now. Executable is working correctly.
Thank you very much for your effort.
