### ISSUE TITLE
Is "libhm_reader_linux64.so" open sourced?

### ISSUE THREAD

**Issue by getwelsim** [OpenRadioss/OpenRadioss#411]
If not, it seems that no one else can build OpenRadioss. At least my Ubutun 20.04 gcc9 shows linking errors about it. No mention of Windows VS+ ifort compilers.

**Comment by OlivierWienholtz** [comment]
Hello,

libhm_reader is enclosed. 
We tested successfully linking on Ubuntu 20.04 on WSL.
I'd be interested to see your linking errors.

**Comment by getwelsim** [comment]
@OlivierWienholtz Thank you for your quick response. 
I just re-cloned the repository and built the projects successfully. The major link error I got previously is "file format not recognized; treating as linker script". I will keep exploring OpenRadioss, a very interesting and visionary open-source project.

**Comment by OlivierWienholtz** [comment]
Glad to see you could build the Starter !
As your issue is solved, I'll close the thread.

Feel free to contact us at any time.
