### ISSUE TITLE
[FR] Porting to Windows 

### ISSUE THREAD

**Issue by luzpaz** [OpenRadioss/OpenRadioss#420]
**Is your feature request related to a problem? Please describe.**
Right now it seems like Linux (per the docs) is the only OS compatible with OpenRadioss. Are there plans to port it to another OS?

**Describe the solution you'd like**
The option for windows users to benefit from OpenRadioss

**Comment by MarianBulla** [comment]
Thanks for your interest in the project and your constructive remark.
We are working on this topic.
As a short term workaround, you can use the WSL (e.g. Ubuntu, which works well on my windows10 machine).
It's desribed in detail in the tutorial: "Getting Started With OpenRadioss and GitHub - Tutorial" on the OpenRadioss confluence page.

**Comment by adrianinsaval** [comment]
sort of related, does this work on macOS? I would assume it would be easier to port to that than to windows.

**Comment by lcheng9** [comment]
@MarianBulla Could you at least release a non-MPI Windows native binary build (*.dll and *.exe files)? if it could be done easier and quicker. Dong this may help the third parties develop pre-/post-processor on Windows.

**Comment by ehan08** [comment]
@MarianBulla Would you like to release the compiler flags for the Intel compilers for Linux and Windows? Thanks.

**Comment by senpaibernd** [comment]
@MarianBulla In my Win-WSL environment (for testing purposes) the following error appears when using starter_linux64_gf:
```
WARNING ID :   1032
**** WARNING STACKSIZE LIMIT IS LOWER THAN 512M**

 .. FUNCTIONS & TABLES
 .. MATERIALS
 .. NODES
 .. PROPERTIES
 .. 3D SHELL ELEMENTS
 .. 3D SPRING ELEMENTS
 .. 3D TRIANGULAR SHELL ELEMENTS
 .. SUBSETS
 .. ELEMENT GROUPS
 .. PART GROUPS
 .. SURFACES
 .. NODE GROUP
 .. BOUNDARY CONDITIONS
 .. INITIAL VELOCITIES
 .. ACCELEROMETERS
 .. DOMAIN DECOMPOSITION
 .. ELEMENT GROUPS
 .. INTERFACES
 .. INTERFACE BUFFER INITIALIZATION
 .. RIGID WALLS
 .. RIGID BODIES
 .. RETURNS TO DOMAIN DECOMPOSITION FOR OPTIMIZATION
 .. DOMAIN DECOMPOSITION
 .. ELEMENT GROUPS
 .. INTERFACES
 .. INTERFACE BUFFER INITIALIZATION

WARNING ID :    343
** WARNING: INITIAL PENETRATIONS IN INTERFACE
 .. RIGID WALLS
 .. RIGID BODIES
 .. ELEMENT BUFFER INITIALIZATION
 .. SECTIONS
Segmentation fault (core dumped)
```

My ENV-Variables here:
```
export OPENRADIOSS_PATH=/home/blind/OpenRadioss_linux64
export RAD_CFG_PATH=$OPENRADIOSS_PATH/hm_cfg_files
export OMP_STACKSIZE=512M
export KMP_STACKSIZE=512M
export LD_LIBRARY_PATH=$OPENRADIOSS_PATH/extlib/hm_reader/linux64/:$OPENRADIOSS_PATH/extlib/h3d/lib/linux64/:$LD_LIBRARY_PATH
export PATH=$PATH:/home/blind/OpenRadioss_linux64/exec
```
Perhaps this will be obsolete as soon as a Win port exists.
BTW: It works perfectly on our Linux server

**Comment by MarianBulla** [comment]
@senpaibernd , can you check your wsl version and the stacksize, please ?
For the wsl version, use the windows standard command window and type "wsl -l -v". Should give you VERSION 2.
For the case you have VERSION 1, you should update to version 2.

For checking the stacksize, use wsl and type "ulimit"

Hope it helps you ?

Yes, reagrding with Win port, we are working on that.

**Comment by senpaibernd** [comment]
@MarianBulla thank you very much! 
I have updated WSL with
```
wsl --set-version Ubuntu-20.04 2
```
**Now it works!**

P.S.: In both cases, the stack size was set to unlimited.

**Comment by MarianBulla** [comment]
@senpaibernd you're welcome!
Yes, I was facing this issue already it the past. It is a limitation (or bug?) in wsl. The stacksize is not passed to wsl version 1.

I'm happy beeing able to help you.

**Comment by luzpaz** [comment]
woot!

**Comment by OlivierWienholtz** [comment]
With Commit Id : ac7886d1cb64d57b80f0347cbb3b3e091eca9d2d
Now the win64 Releases are done.
windows is fully available
