### ISSUE TITLE
Issue with linking libmetis_linux64_gcc.a

### ISSUE THREAD

**Issue by swaggyliu** [OpenRadioss/OpenRadioss#424]
**Describe the bug**
When I compile the starter in ubuntu 20.04, it fails in linking **libmetis_linux64_gcc.a** 

**To Reproduce**
run ./build_script.sh -arch=linux64_gf

**Desktop (please complete the following information):**
gcc version = 10.3.0
gfortran version = 9.4.0
cmake version = 3.16.3

**Additional context**
No

**Comment by Hedilict** [comment]
Same issue.

**Comment by laurent-altr** [comment]
Hi, 

Note that this library is stored using git lfs.  

Could you try `git lfs fetch --all` and compile again?

If that does not work, please send the log. 

Thank you,
Laurenr

**Comment by swaggyliu** [comment]
> Hi,
> 
> Note that this library is stored using git lfs.
> 
> Could you try `git lfs fetch --all` and compile again?
> 
> If that does not work, please send the log.
> 
> Thank you, Laurenr

Thank you, it works.
