### ISSUE TITLE
[FR] Add `.git-blame-ignore-revs` to omit commits that may be considered to pollute the repo git log/blame

### ISSUE THREAD

**Issue by luzpaz** [OpenRadioss/OpenRadioss#500]
**Is your feature request related to a problem? Please describe.**
Certain commits may pollute the `git log` output or at least irk some folks who view it that way.

**Describe the solution you'd like**
Github allows the use of a `.git-blame-ignore-revs` file. Here's the background ([link](https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/)). Essentially the file consists of commit hashes that the project would prefer to be omitted from the repo `git blame`.

I'll be submitting a PR that will address past typo fixes to be included in said `.git-blame-ignore-revs`   
JFYI, the command I used to ascertain said commits was:  
```shell
$ git log --oneline --no-abbrev-commit | grep typos
ec64eee54bab8d011ebf024a0e052a43a6617be2 Fix typos in starter/source/interfaces subdir
f22ff42b348f2a4031489975611849422aa37f7f Fix typos in starter/source/properties subdir
6e9837361fcee23e6c6cd39b8b4a421e5f406cc3 Fix typos in starter/source/elements subdir
591fcb9df0f8aacfddd5c3f08437f512e4bf96ce Fix typos in starter/source/materials subdir
```

**Comment by laurent-altr** [comment]
Hi @luzpaz, 

I like the idea of having a list of commits that can be ignored.
Personally, I would prefer having this list somewhere in `./scripts`:

- I would prefer having all the revisions on github: some people my be interested in such changes.
- I don't mind typing `git blame --ignore-revs-file ./scripts/ignore-revs.txt <filename>` when needed

**Comment by luzpaz** [comment]
All good. Not sure Github will know to look in scripts/ though (it may be hardcoded to look for it in the top level directory. I've updated the PR per your preference.
