### ISSUE TITLE
Builing Starter fails (Cent OS 7.9)

### ISSUE THREAD

**Issue by BastiLoe** [OpenRadioss/OpenRadioss#555]
**Describe the bug**
1. gfortran does not know option "fdec-math". Can be solved by deleting this out of "cmake_linux64_gf.txt"
2. After 9% of compilation I get:
`OpenRadioss/OpenRadioss/starter/share/spe_inc/vectorize.inc:42.6:
    Included at /det07a/BL/OpenRadioss/OpenRadioss/starter/source/elements/sh3n/coquedk/cdkfint_reg_ini.F:215:

*$OMP SIMD
      1
Error: Unclassifiable OpenMP directive at (1)
/det07a/BL/OpenRadioss/OpenRadioss/starter/share/spe_inc/vectorize.inc:42.6:
    Included at /det07a/BL/OpenRadioss/OpenRadioss/starter/source/elements/sh3n/coquedk/cdkfint_reg_ini.F:253:
`

**To Reproduce**
run ./build_script.sh -arch=linux64_gf

**Expected behavior**
Should compile

**Comment by BastiLoe** [comment]
Seems GCC/gfortran supplied with Cent OS 7.9 is way to old, as gfortran 8 or higher is required. WIll try to update.

**Comment by MarianBulla** [comment]
Thank you very much for your effort. 
Please let us know, if it will work on your side after your compiler update.

**Comment by OlivierWienholtz** [comment]
Indeed, GCC/Gfortan 8 or higher is requested. 

I close the issue.
Thank You
