### ISSUE TITLE
openradioss can not use multi cores in one process

### ISSUE THREAD

**Issue by yaolang-hpc** [OpenRadioss/OpenRadioss#680]
![image](https://user-images.githubusercontent.com/24679259/197960375-b964136b-8e08-4734-a3bf-7efef8e7e68b.png)
![image](https://user-images.githubusercontent.com/24679259/197960439-0711b7c3-d200-4d38-bac3-d494cc827fa6.png)
I use export OMP_NUM_THRTEADS=4 
and mpirun -np 16 --allow-run-as-root ./engine_linux64_gf_ompi -nt 4 -i CamryOpenRadioss_0001.rad
but when I use top command and find every process only use one core not four cores.
I want to know how to solve the problem.

**Comment by OlivierWienholtz** [comment]
Hello,
Based on your experience, we have modified the INSTALL.md documentation, how run OpenRadioss for Linux document.
See : 41102741a56d41b727ccbab6f53876d8b5b46d67
