### ISSUE TITLE
”undefined reference to symbol“ when compiling starter

### ISSUE THREAD

**Issue by cdasl** [OpenRadioss/OpenRadioss#694]
**Describe the bug**
When I compile the starter in ubuntu 20.04 WSL, it fails in linking Fortran executable starter_linux64_gf
![image](https://user-images.githubusercontent.com/30762866/198827918-3d48e182-1865-4925-99e2-a807bb3815e1.png)

**To Reproduce**
run ./build_script.sh -arch=linux64_gf in starter folder

**Desktop (please complete the following information):**
gcc version = 9.4.0
gfortran version = 9.4.0
cmake version = 3.16.3

Additional context
No

**Comment by OlivierWienholtz** [comment]
Hi,
We tested on Ubuntu 20.04 / WSL it is working fine.
I believe the g++ / runtime compiler is missing. 
Pls try:
sudo apt install build-essential

Hope it helps,

**Comment by cdasl** [comment]
Thank you! It solved when I compiled in `/home/my_user_name/` folder.
