### ISSUE TITLE
Visual Studio 2019 compile errors on windows system

### ISSUE THREAD

**Issue by dwyanexu419** [OpenRadioss/OpenRadioss#695]
Hello, I have installed Visual studio 2019 and intel oneAPI 2022 in my windows system. The environment of openRadioss on windows is built with cygwin, and the make package and perl package are installed in cygwin. The Visual studio solution can be built successfully, however, when the solution is opened for build with vs2019, an MSB8066 error is reported with exit code 9009. I don't know how to fix this error？
thank you!

**Comment by dwyanexu419** [comment]
The build log says: 'perl' is not an internal or external command, nor is it a runnable program. But I have installed perl package in cygwin

**Comment by OlivierWienholtz** [comment]
I am wondering where cmake come from. We made good experience using the cmake released with VS2019...
PATH variable are exported between cygwin & DOS, so cmake from VS finds it...

in cygwin : type 
which cmake
which perl 

cmake should be found in VS Path
perl in /bin/perl.exe

Hope it helps

**Comment by dwyanexu419** [comment]
@OlivierWienholtz ,thanks for your help.With your help, both cmake and perl have been configured correctly in my environment. But when I start the building with the following command: "./build_script.sh -arch=win64". The error shown in the picture occurs,
"C:/cygwin64/home/zm/OpenRadioss-main/starter/source/output/analyse/analyse.c(277,3): error: call to undeclared function 'WISTDO'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  wistdo(&nb_int, tab_int);"

 and there are more than a dozen similar errors. I don't know how to solve this problem. thanks!
![image](https://user-images.githubusercontent.com/51504916/200164335-696bef5a-3ade-4371-8d2f-e8eca7c5d5fd.png)

**Comment by OlivierWienholtz** [comment]
Hello, this is a good news that you have been able to setup Cygwin properly.

One Question : what is the OneAPI version you used ?
Id'like to have a look at the full log of cmake.

Can you pls copy past the stdout of cmake, that I can see how it was confugred ? 
The best would be to delete cbuild_win64 directory & start from scratch.

Thank You

**Comment by bocaj2222** [comment]
Hi @OlivierWienholtz . I just wanted to mention I ran into the same problem as @dwyanexu419 . I am using OneAPI 2022.3, which is the most recent version and the only one available for download it appears.

**Comment by drussell247** [comment]
Hello @OlivierWienholtz ,

Same issue here using VS2019 & OneAPI 2022.3, please find attached the output. VS2022 also failed to compile.

[stdout.txt](https://github.com/OpenRadioss/OpenRadioss/files/9947385/stdout.txt)

Thank You

**Comment by OlivierWienholtz** [comment]
Looks like Warnings in OneAPI 2022.1 become errors in OneAPI 2022.3
I need to fix them.

**Comment by dwyanexu419** [comment]
Hello @OlivierWienholtz , 
I used VS2019 & OneAPI 2022.3, and the stdout of cmake is same as @DavidR-Vortex

**Comment by OlivierWienholtz** [comment]
I did some changes in the Starter regarding your issue, with commit  : fb2cb8c97d8ef2a4470aeb1b8f996b33ab8caf02

Pls update & retry.

**Comment by bocaj2222** [comment]
@OlivierWienholtz, thanks for looking into this. It got a little further for me, be errored out at about 99%.
![image](https://user-images.githubusercontent.com/78292023/200386577-065d6864-61df-41b6-9ac0-414dc81b47af.png)

**Comment by OlivierWienholtz** [comment]
Thank You for your comment. 
Fix for this is in Pull Request #730

**Comment by DavidR-Vortex** [comment]
Implemented the change made in Pull Request #730 - successful build

Many Thanks @OlivierWienholtz

**Comment by bocaj2222** [comment]
@OlivierWienholtz, successful build for me too, thanks. Unfortunately, I get a Radioss Error ID 760 on any starter file I try to use (including example files). This doesn't happen for me with the precompiled linux version in WSL2 (fb2cb8c).

**Comment by DavidR-Vortex** [comment]
This might be unrelated but I had to add %OPENRADIOSS_PATH%\extlib\intelOneAPI_runtime\win64 to PATH in order for starter to pick-up all libraries, current documentation only sets PATH=%OPENRADIOSS_PATH%\extlib\hm_reader\win64;%OPENRADIOSS_PATH%\extlib\h3d\lib\win64;%PATH%

**Comment by DavidR-Vortex** [comment]
I managed to replicate your error, @bocaj2222. and resolved it by updating the provided mkl_intel_thread.2.dll in %OPENRADIOSS_PATH%\extlib\intelOneAPI_runtime\win64 with mkl_intel_thread.2.dll from the OneAPI installation I used to compile. In my case I used.

"C:\Program Files (x86)\Intel\oneAPI\mkl\2022.2.0\redist\intel64\mkl_intel_thread.2.dll"

**Comment by bocaj2222** [comment]
@DavidR-Vortex , thanks for sharing. For some reason it still gives me the same error using that version of the "mkl_intel_thread.2.dll". Actually I didn't realize there was another version in the openradioss folder, so I pointed my path to the oneapi installation originally.

**Comment by DavidR-Vortex** [comment]
OK just for clarity my env variable are defined as follows:

set OPENRADIOSS_PATH=C:\Users\David\Open_Radioss\
set RAD_CFG_PATH=%OPENRADIOSS_PATH%\hm_cfg_files
set KMP_STACKSIZE=400m
set PATH=%OPENRADIOSS_PATH%\extlib\hm_reader\win64;%OPENRADIOSS_PATH%\extlib\h3d\lib\win64;%OPENRADIOSS_PATH%\extlib\intelOneAPI_runtime\win64;%PATH% 

@OlivierWienholtz I have not been able to successfully set my H3D library path using the above for use in engine (I've also tried setting RAD_H3D_PATH). placing h3dwriter.dll in the local directory however has enabled me to run bird strike to completion, is there an environment variable that I may have missed?

**Comment by OlivierWienholtz** [comment]
Hello,
First of All, glad to hear you were able to build OpenRadioss on Windows.

So, the runtimes we packed come from OneAPI 2022.2, 
OpenRadioss releases for Windows are comming soon. It is intended to the Releases, so when you 
I need to add some notes there to avoid confusion.

As you have built with OneAPI 2022.3, the runtimes packed there are too old.
I recommend that you use a Shell / Load a Shell with your compiler installation.
Typically in a Batch shell : 
call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2019

This will load the runtime libraries from the compiler you used....


---

About H3D
H3D has a dynamic load & is not in the shell...
setting RAD_H3D_PATH should work.

**Comment by OlivierWienholtz** [comment]
The issue here was mainly how to build OpenRadioss in your environment.
It is solved with Commit ID : 6c2e8fb41ccd5a50493722cecfe92cd802f2bca5
