### ISSUE TITLE
how to use intel mkl library to accelerate the fortran program on linux os

### ISSUE THREAD

**Issue by yaolang-hpc** [OpenRadioss/OpenRadioss#705]
when I compile the openradioss，I found it can only support gcc+ompi on linux os.but intel mkl library could accelerat sharply the fortran program.
so I want to know how to compile openradioss by intel compiler and intempi.
Look forward to your reply.
![1667374152934](https://user-images.githubusercontent.com/24679259/199426425-d4e52066-bbe3-491a-b494-f30a0fe025cc.png)

**Comment by laurent-altr** [comment]
Hi @yaolang-hpc, 
We do not support Intel compilers for Linux yet, but we have already started to work on it.
Anyway, I do not expect major performance improvement using MKL (blas/lapack is not extensively used in OpenRadioss, unless you are using the implicit feature).

**Comment by laurent-altr** [comment]
The support for Intel OneAPI compiler has been added.
