### ISSUE TITLE
h3d files do not contain any Sets as HyperView Player show

### ISSUE THREAD

**Issue by AlexanderKazantchev** [OpenRadioss/OpenRadioss#795]
Hello!
I have an engine rad-file with (for example):

/H3D/DT
0 0.000275
/H3D/NODA/DT
/H3D/ELEM/DT

Official HVP show that h3d-files has no any Sets. There are only part at every timestep.
I can not to test h3d-files at commercial HyperView, then I don't know if this error lies in HVP or in OpenRadioss engine.

**Comment by sebastienVilleneuve** [comment]
Hi @AlexanderKazantchev 

It is not available only in HVP .

Regards,
Sébastien

**Comment by AlexanderKazantchev** [comment]
Thank you!
