### ISSUE TITLE
ANIM_SHELL_THIN card

### ISSUE THREAD

**Issue by AlexanderKazantchev** [OpenRadioss/OpenRadioss#806]
Hello!
For metalforming processes simulations I have try to include to results database a thinning of sheets in simulation with the card
/ANIM/SHELL/THIN .
Solver is working with it, but when I've open with windows ParaView 5.9.1 any vtk-files, converted from A-files, the thinning results always return an error "Could not determine array range", and the name of such results has undefined symbol: "2DELEM_?inning". At the same time the older ParaView versions (5.4.0 for example) have no any thinning results.

**Comment by OpenDevAccount** [comment]
Hi,

Certainly because text of the output contains '%' 

![Screenshot_20221119-185648_GitHub.jpg](https://user-images.githubusercontent.com/52290489/202864985-ba83c9ac-142a-4a54-a546-0dd637dbbe57.jpg)

You can try modifying it.

Sebastien

**Comment by AlexanderKazantchev** [comment]
Thank you! It works well after editing and recompilation

**Comment by AlexanderKazantchev** [comment]
Thank you! It works well after editing and recompilation
