### ISSUE TITLE
fixing AMD AOCC-4.0.0 build issues

### ISSUE THREAD

**Issue by jhasbestan** [OpenRadioss/OpenRadioss#816]
Hi All

I have forked the repo and have a branch that fixes the build problems with AMD's newly released AOCC-4.0.0 
I will submit a pull request shortly. 
I opened this issue to follow the steps as you required per contributing.md document.

Thanks

**Comment by sebastienVilleneuve** [comment]
https://github.com/OpenRadioss/OpenRadioss/pull/826

**Comment by jhasbestan** [comment]
Thanks for review and merge
