### ISSUE TITLE
** ERROR IN INPUT FORMAT

### ISSUE THREAD

**Issue by tjc0726** [OpenRadioss/OpenRadioss#819]
**Describe the bug**
Run successfully in commercial version of radioss 2021.2,but no in openradioss

ERROR ID :     55
** ERROR IN INPUT FORMAT
DESCRIPTION :  
   -- OPTION: 
   -- BLOCK:
   -- LINE: 
**To Reproduce**
run starter_win64.exe -i \***\***\ult_0000.rad

**Output**

change .txt to .out
[ult_0000.txt](https://github.com/OpenRadioss/OpenRadioss/files/10062348/ult_0000.txt)

**Desktop (please complete the following information):**
 - Version [commit id] [20221118]
- Hardware [which CPU] Xeon Sliver 4120R*2
- Configuration [number of OpenMP threads, and MPI tasks]
- nt 1
- set OMP_NUM_THREADS=[N]

**Additional context**
model in here,has been morphed due to censor requirement
change .txt to .rad
[ult_0000.txt](https://github.com/OpenRadioss/OpenRadioss/files/10062392/ult_0000.txt)
[ult_0001.txt](https://github.com/OpenRadioss/OpenRadioss/files/10062393/ult_0001.txt)

**Comment by sebastienVilleneuve** [comment]
Hi @tjc0726 ,

Can you retry with latest build ?

Thanks,
Sébastien
