### ISSUE TITLE
Engine executable help message contains "Starter" for -input

### ISSUE THREAD

**Issue by lcheng9** [OpenRadioss/OpenRadioss#904]
**Describe the bug**
Engine executable help message shows "Starter" input file for the -input argument

**To Reproduce**
run the engine_win64.exe with no argument.

**Expected behavior**
Show the word of "Engine" instead of "Starter".

**Output**
A screen capture is attached.

**Desktop (please complete the following information):**
 - Official build Dec. 12. 2022

**Additional context**
This is minimal.

![Capture_or](https://user-images.githubusercontent.com/106984354/207666631-ce0fa062-7b66-47c1-aea0-68ddecf1360d.PNG)

**Comment by MarianBulla** [comment]
Hello, 
This is great ! 
Thank you very much for this catch.
It will be fixed, soon.

Again, thank you very much for this.

Thanks and best regards,
Marian

**Comment by lcheng9** [comment]
@MarianBulla Thank you.
