### ISSUE TITLE
INT_BEAM, typo in Manual, bad response for ISECT=2, NITR=2

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#926]
**Describe the bug**
The bending moment in a beam should be the inverse of the reaction moment.
With INT_BEAM, ISECT=2, NITR=2 section, there is a high deviation.
The Radioss Reference Guide has in the description /ANIM/BEAM maybe a typo for the plastic strains.

**To Reproduce**
Run the model and compare the bending moment of element 2111 as in the figure in the attached pdf.

**Expected behavior**
Correction of the manual regarding EPSP vs. ESPN/N. Extent the section description, give a warning in
the manual for the mentioned plastic beam.

**Output**
A pdf file with detailed explanations and the Radioss files are in the archive.

**Desktop (please complete the following information):**
 - Version 6cf5b4396902227509b7b44411cddd9dc6df4c46
- Hardware Intel
- Configuration SMP with one thread

**Additional context**

**Comment by SonSiont** [comment]
[beamissue.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/10266881/beamissue.tar.gz)

**Comment by bertrand-altair** [comment]
Issue was investigated, and a report written 
[Radioss_Beam_report.docx](https://github.com/OpenRadioss/OpenRadioss/files/11089251/Radioss_Beam_report.docx)
