### ISSUE TITLE
T01/csv file misses the last timestep data

### ISSUE THREAD

**Issue by lcheng9** [OpenRadioss/OpenRadioss#933]
**Describe the bug**
The converted csv file misses the last time data, checked the th_to_csv.exe source code, which looks fine for me, so I suspect the T01 file has no such data. A 10-step analysis should have 11 time steps if including the initial time zero step. The animation result file is generated correctly, while the T01 file not. 

**To Reproduce**
Run a small test with /TH/ in the starter file. Or use the attached scripts. 

**Expected behavior**
T01/csv file has the last time step. For the attached case, data at time 0.01 should exist.

**Output**
Attached.

**Desktop (please complete the following information):**
 - Win64, AMD 7950x, 36 OpenMP threads.

![radioss_csv_screen](https://user-images.githubusercontent.com/106984354/208768830-cd544af4-2110-4bf5-a919-13fe74537ccb.PNG)

[mesh_radioss.inc.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272730/mesh_radioss.inc.txt)
[radioss_welsim_0000.rad.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272725/radioss_welsim_0000.rad.txt)
[radioss_welsim_0001.rad.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272728/radioss_welsim_0001.rad.txt)
[radioss_welsim_0000.out.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272755/radioss_welsim_0000.out.txt)
[radioss_welsim_0001.out.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272754/radioss_welsim_0001.out.txt)

[radioss_welsimT01.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272719/radioss_welsimT01.txt)
[radioss_welsimT01.csv](https://github.com/OpenRadioss/OpenRadioss/files/10272721/radioss_welsimT01.csv)
[radioss_welsimA011.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272720/radioss_welsimA011.txt)
[radioss_welsim_A011.vtk.txt](https://github.com/OpenRadioss/OpenRadioss/files/10272723/radioss_welsim_A011.vtk.txt)

**Comment by sebastienVilleneuve** [comment]
@lcheng9 
Yes I confirm , You're right last time ( 0.01)  is missing in T01 file , not in anim files.
we have some mechanism to write 'last' animation file before end of computation , I think that is missing for TH.

As a workaround , you can define time for end of the run ( in /RUN) to 0.0101 .
I let you test and confirm.

Thanks,
Sébastien

**Comment by lcheng9** [comment]
@sebastienVilleneuve Thank you so much for your quick response and suggested workaround. look forward to testing the complete TH data.
