### ISSUE TITLE
Rename anim Axxx file index from 1-based to 0-based

### ISSUE THREAD

**Issue by lcheng9** [OpenRadioss/OpenRadioss#934]
**Describe the bug**
The generated Axxx file starts with A001, which isn't intuitive since the first anim file is about time 0.

**To Reproduce**
Any engine file that contains /ANIM/, or uses the scripts attached.

**Expected behavior**
The first generated anim file should be like xxxA000, and the last generated anim file index matches the number of the time steps.

**Output**
A screenshot is attached.

**Desktop (please complete the following information):**
Win64, AMD 7950x, 32 OpenMP threads.

![radioss_vtk_screen](https://user-images.githubusercontent.com/106984354/208802524-c74d840e-277c-49e6-a6d3-6224a84134ab.PNG)

[radioss_welsimA001.txt](https://github.com/OpenRadioss/OpenRadioss/files/10273898/radioss_welsimA001.txt)
[radioss_welsim_A001.vtk.txt](https://github.com/OpenRadioss/OpenRadioss/files/10273897/radioss_welsim_A001.vtk.txt)

[mesh_radioss.inc.txt](https://github.com/OpenRadioss/OpenRadioss/files/10273930/mesh_radioss.inc.txt)
[radioss_welsim_0000.rad.txt](https://github.com/OpenRadioss/OpenRadioss/files/10273899/radioss_welsim_0000.rad.txt)
[radioss_welsim_0001.rad.txt](https://github.com/OpenRadioss/OpenRadioss/files/10273901/radioss_welsim_0001.rad.txt)

**Comment by elequiniou** [comment]
Hi Icheng9,

This one is not an issue. This was always the case that animation written by Engine starts with A001 (first animation of the Engine run). This sounded logic to Fortran progs at that time ;-) Besides that, the A000 is reserved for Starter which is a special animation file that contains info for some specific usages.

I propose to move this issue under discussion which sounds more appropriate place.

Thanks for your understanding,

Eric

**Comment by elequiniou** [comment]
Sounds good, thank you for adapting to existing mechanism, so I'll close the issue.
