### ISSUE TITLE
LS-DYNA input etype selection and /TFILE parameter setting is not working

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#944]
**Describe the bug**
Some problems occur when running with LS-DYNA input files.
1. a fully integrated hex element cannot be selected.
2. neither loading nor the /TFILE parameters work with *INCLUDE_TRANSFORM
        /TFILE/4
        0
        /RFILE
        0
        /RFILE
        0

3. in the output file the *CONTROL_UNITS is not reported
    WORK UNIT SYSTEM . . . . . . ( N.A, N.A, N.A ) 1.0000000000000E+00 1.0000000000000E+00 1.0000000000000E+00
    INPUT UNIT SYSTEM  . . . . . ( N.A, N.A, N.A ) 1.0000000000000E+00 1.0000000000000E+00 1.0000000000000E+00
    UNIT SYSTEM, ID = 1000000001 ( N.A, N.A, N.A ) 1.0000000000000E+00 1.0000000000000E+00 1.0000000000000E+00

**To Reproduce**
Run the job
$OPENRADIOSS_SOURCE_PATH/exec/engine_linux64_gf -i Start.k -nt 1
and look into Start_0001.rad and Start_0000.out

**Expected behavior**
1.
    The LS-DYNA element type 2 should translatet into Isolid 14/18
2.
    /TFILE/4
    0.0005
3.
    WORK UNIT SYSTEM . . . . . . ( Mg , mm , s   ) 1.0000000000000E+03 1.0000000000000E-03 1.0000000000000E+00
    INPUT UNIT SYSTEM  . . . . . ( Mg , mm , s   ) 1.0000000000000E+03 1.0000000000000E-03 1.0000000000000E+00

**Output**
The input files are in the attached archive.

**Desktop (please complete the following information):**
- Version: 3a18bf2b1492d8b5432259c924db039f5031e46e
- Hardware: Intel with gcc on linux
- Configuration: 1 OpenMP threads, and 1 MPI tasks

**Additional context**
The include conrad_0000.rad and conrad_0001.rad show a possible solution
[elemissue.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/10298767/elemissue.tar.gz)

**Comment by sebastienVilleneuve** [comment]
Hi @SonSiont 

Thank you for reporting this problem , I will have a look to this. (I am able to reproduce)

Thanks,
Sébbastien

**Comment by SonSiont** [comment]
Hi Sébastien,

I have made a rerun and I see a full integrated brick. I am not sure what I detected in the past.

Thanks,
SonSiont

**Comment by sebastienVilleneuve** [comment]
Hi @SonSiont 

This part of the code is quickly evolving , I think we made this enhancement recently.

Thanks
Sébastien

**Comment by sebastienVilleneuve** [comment]
Hi @SonSiont 

point 3. is now solved : 
![image](https://user-images.githubusercontent.com/100404030/222358140-87047298-4e2b-47a8-973b-ccbd2c5e2856.png)

**Comment by sebastienVilleneuve** [comment]
Hi @SonSiont 

related to 2.
you have several *DATABASE cards with no DT defined.


Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
Hi all issues are closed or understood, I close this issue.

Thanks,
Sébastien
