### ISSUE TITLE
Initial velocity in a LS-DYNA model is not working

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#990]
**Describe the bug**
A LS-DYNA model with initial rotations is not rotating.
In flying_solid_0000.out:
`     INITIAL VELOCITIES    
     -------------------    
         NODE                      VX                  VY                  VZ                 VRX                 VRY                 VRZ

 NUMBER OF NODES WITH INITIAL VELOCITY:         0    
`
[flying_solid.k.gz](https://github.com/OpenRadioss/OpenRadioss/files/10399159/flying_solid.k.gz)

**To Reproduce**
Run starter and engin

**Expected behavior**
It should rotate

**Output**
LS-DYNA file is in the attachment

**Desktop (please complete the following information):**
  Linux 64 bits, GNU compiler
  git 96f63c1ff23ab7f8d063ab3392a905481ec03dc4
  Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64)
  NUMBER OF HMPP PROCESSES     1

**Additional context**
When do an init with velocities, it works.

**Comment by sebastienVilleneuve** [comment]
@SonSiont 

solids don't have rotational dof , that's why, applying rotational velocities to solid nodes does not have any effect.

Thanks,
Sébastien

**Comment by sebastienVilleneuve** [comment]
No possible to have rotational dof on Solids in Radioss

Sébastien
